### ISSUE TITLE
NPE in RaftPartitionServer

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#6708] opened 2021-03-31 11:08 UTC
**Describe the bug**
NPE occurred in benchmarks. Looks like a shutdown while we are starting situation.

https://console.cloud.google.com/errors/CNS5wb7Io4jAnQE?service=zeebe-broker&version=medic-cw-13-553958a93-benchmark&time=P7D&project=zeebe-io&folder&organizationId=669107107215

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: null
	at io.atomix.raft.partition.impl.RaftPartitionServer.stop(RaftPartitionServer.java:141) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.closeServer(RaftPartition.java:165) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.close(RaftPartition.java:155) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.close(RaftPartitionGroup.java:221) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.stop(DefaultPartitionService.java:102) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.core.Atomix.stopServices(Atomix.java:186) ~[atomix-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.cluster.AtomixCluster.stop(AtomixCluster.java:289) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.Broker.lambda$atomixCreateStep$13(Broker.java:262) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.CloseProcess.lambda$closingStepByStep$0(CloseProcess.java:59) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.CloseProcess.closingStepByStep(CloseProcess.java:59) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.CloseProcess.closeReverse(CloseProcess.java:40) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:83) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.Broker.internalStart(Broker.java:180) ~[zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.Broker.start(Broker.java:160) [zeebe-broker-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) [zeebe-distribution-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806) [spring-boot-2.4.4.jar:2.4.4]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:790) [spring-boot-2.4.4.jar:2.4.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.4.jar:2.4.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313) [spring-boot-2.4.4.jar:2.4.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) [spring-boot-2.4.4.jar:2.4.4]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:47) [zeebe-distribution-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```
</p>
</details>

<details><summary>Log</summary>
 <p>

```
D 2021-03-31T09:44:52.079921Z Loaded disk segment: 5070 (raft-partition-partition-3-5070.log) 
D 2021-03-31T09:44:52.080343Z Found segment: 5070 (raft-partition-partition-3-5070.log) 
D 2021-03-31T09:44:52.402070Z Loaded disk segment: 5075 (raft-partition-partition-3-5075.log) 
D 2021-03-31T09:44:52.402579Z Found segment: 5075 (raft-partition-partition-3-5075.log) 
E 2021-03-31T09:44:52.561400Z Bootstrap Broker-2 [6/13]: cluster services failed with unexpected exception. 
I 2021-03-31T09:44:52.573775Z Closing Broker-2 [1/5]: subscription api 
D 2021-03-31T09:44:52.575438Z Closing Broker-2 [1/5]: subscription api closed in 1 ms 
I 2021-03-31T09:44:52.575681Z Closing Broker-2 [2/5]: command api handler 
D 2021-03-31T09:44:52.576550Z Closing Broker-2 [2/5]: command api handler closed in 1 ms 
I 2021-03-31T09:44:52.576740Z Closing Broker-2 [3/5]: command api transport 
I 2021-03-31T09:44:52.601Z RaftServer{raft-partition-partition-3}{role=FOLLOWER} - No heartbeat from null in the last PT3.709S (calculated from last 3709 ms), sending poll requests 
W 2021-03-31T09:44:52.601844Z RaftServer{raft-partition-partition-3}{role=FOLLOWER} - Poll request to 0 failed: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-03-31T09:44:52.602064Z RaftServer{raft-partition-partition-3}{role=FOLLOWER} - Poll request to 2 failed: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
D 2021-03-31T09:44:52.716687Z Created segment: JournalSegment{id=127, version=1, index=197837911} 
D 2021-03-31T09:44:53.013763Z Loaded disk segment: 6910 (raft-partition-partition-3-6910.log) 
D 2021-03-31T09:44:53.014555Z Found segment: 6910 (raft-partition-partition-3-6910.log) 
D 2021-03-31T09:44:53.030933Z Created segment: JournalSegment{id=3, version=1, index=195093091} 
D 2021-03-31T09:44:53.964957Z Created segment: JournalSegment{id=7228, version=1, index=202431955} 
D 2021-03-31T09:44:54.023441Z Created segment: JournalSegment{id=7228, version=1, index=202431955} 
D 2021-03-31T09:44:54.183596Z Loaded disk segment: 6967 (raft-partition-partition-3-6967.log) 
D 2021-03-31T09:44:54.184355Z Found segment: 6967 (raft-partition-partition-3-6967.log) 
I 2021-03-31T09:44:54.595833Z Stopped 
D 2021-03-31T09:44:54.596430Z Closing Broker-2 [3/5]: command api transport closed in 2020 ms 
I 2021-03-31T09:44:54.596821Z Closing Broker-2 [4/5]: membership and replication protocol 
E 2021-03-31T09:44:54.597808Z Closing Broker-2 [4/5]: membership and replication protocol failed to close. 
```

</p>
</details>

<details><summary>Stacktrace of Preceding Error in Log</summary>
 <p>

```
java.util.concurrent.CompletionException: io.zeebe.journal.file.record.CorruptedLogException: Record doesn't match checksum. Log segment may be corrupted.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[atomix-utils-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: io.zeebe.journal.file.record.CorruptedLogException: Record doesn't match checksum. Log segment may be corrupted.
	at io.zeebe.journal.file.record.JournalRecordReaderUtil.read(JournalRecordReaderUtil.java:68) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.MappedJournalSegmentWriter.reset(MappedJournalSegmentWriter.java:222) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.MappedJournalSegmentWriter.<init>(MappedJournalSegmentWriter.java:63) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.JournalSegment.createWriter(JournalSegment.java:153) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.JournalSegment.<init>(JournalSegment.java:57) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.SegmentedJournal.newSegment(SegmentedJournal.java:441) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.SegmentedJournal.loadSegment(SegmentedJournal.java:452) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.SegmentedJournal.loadSegments(SegmentedJournal.java:500) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.SegmentedJournal.open(SegmentedJournal.java:206) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.SegmentedJournal.<init>(SegmentedJournal.java:79) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.journal.file.SegmentedJournalBuilder.build(SegmentedJournalBuilder.java:136) ~[zeebe-journal-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.storage.log.RaftLog$Builder.build(RaftLog.java:321) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.storage.RaftStorage.openLog(RaftStorage.java:242) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.<init>(RaftContext.java:155) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:257) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:231) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:175) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.initServer(RaftPartitionServer.java:145) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:103) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:119) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:201) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:203) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[atomix-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
```

</p>
</details>

**Environment:**
 - OS: Linus
 - Zeebe Version: 1.0.0-alpha3
 - Configuration: Benchmark

**Comment by npepinpe** [comment] 2021-04-07 07:59
Duplicate of https://github.com/camunda-cloud/zeebe/issues/5645

**Closed by npepinpe** 2021-04-07 07:59 UTC
Labels: Status: Backlog, Type: Bug
