### ISSUE TITLE
Zeebe stops exporting to elasticsearch after update

### ISSUE THREAD

**Issue by gschelter** [camunda-cloud/zeebe#8715] opened 2022-02-02 12:41 UTC
**Describe the bug**
We are using Zeebe with the elasticsearch exporter. We updated from 1.0.1 directly to 1.3.2. Since then no data is exported to elasticsearch. The broker runs fine and logs "Exporter opened". There is just nothing inserted in elasticsearch.
We confirmed the elasticsearch cluster is up and running and the connection config is correct.

**Expected behavior**
Process data should be exported to Elasticsearch like before.

**Log/Stacktrace**

[logs.txt](https://github.com/camunda-cloud/zeebe/files/7986405/logs.txt)

</p>
</details>

**Environment:**
 - OS: Docker official image
 - Zeebe Version: 1.3.2
 - Configuration: 
[application.yaml.txt](https://github.com/camunda-cloud/zeebe/files/7986403/application.yaml.txt)

**Comment by oleschoenburg** [comment] 2022-02-03 09:13
@gschelter Thank you for reporting. 

AFAIK there are no known bugs that would explain this and from the Zeebe logs you have provided nothing stands out as problematic, so to diagnose this I'd like to request a bit more information if possible. 
Particularly interesting would be:
- Elasticsearch version and logs
-  More Zeebe logs. It looks like the Zeebe logs you have provided are only covering the startup of the broker. It'd be interesting to see more logs during actual processing because that's when Zeebe should try to export. 

If you think the Zeebe logs don't contain anything interesting you could enable debug logs for Zeebe: https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/logging/#change-log-level-dynamically

**Comment by gschelter** [comment] 2022-02-03 15:22
Here are the logs of several hours: [extract-2022-02-03T15 13 43.130Z.csv](https://github.com/camunda-cloud/zeebe/files/7995756/extract-2022-02-03T15.13.43.130Z.csv)
Zeebe is set to logging level debug, I removed all "Detected 'HEALTHY' components" lines for clarity.

We are running Elasticsearch v7.14.1. Unfortunately I'm unable to export the logs right now as we are using the managed Elastic Cloud service.

**Comment by oleschoenburg** [comment] 2022-02-03 15:33
Thank you! From the logs it looks like Zeebe is exporting. See for example:

```
"2022-02-01T23:39:46.919Z","production-databases-zeebe","debug",,"Current commit position 134828349 >= 134828349, committing snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/pending/54549862-7-134828345-134828348, checksum=2785830940, metadata=FileBasedSnapshotMetadata{index=54549862, term=7, processedPosition=134828345, exporterPosition=134828348}}."
```
where processed and exported position are basically equal.

Can you clarify what you mean with "There is just nothing inserted in elasticsearch"? What elasticsearch indices are you looking at?

**Comment by gschelter** [comment] 2022-02-03 16:40
It seems like you are right and there is data exported to Elasticsearch. At least for the index zeebe-record_process-instance_1.3.3_2022-02-03 I can find new entries.
I fired up the Operate Dashboard again but it doesn't display any data from after the update, so it seems the issue is not related to Elasticsearch, but Operate failing to displaying or migrating the data. The logs show a lot of failed migration attempts:
[operate-logs.csv](https://github.com/camunda-cloud/zeebe/files/7996462/operate-logs.csv)

I restarted Operate to get fresh logs. We are now running 1.3.3 on the cluster and Operate.

**Comment by oleschoenburg** [comment] 2022-02-03 17:07
Thank you for confirming :+1: 
Then I'm closing this for now as the issue is not with Zeebe. I'd recommend for you to open a support case for the issues with Operate.

**Closed by oleschoenburg** 2022-02-03 17:07 UTC
Labels: Type: Bug, Status: Needs Information

**Comment by Zelldon** [comment] 2022-02-03 17:22
@oleschoenburg could you please open an issue imternally? 

Lets travk the progress also here so users have some visibility https://forum.camunda.io/t/certain-workflows-are-not-showing-in-operate-ui/2598

**Comment by gschelter** [comment] 2022-02-03 17:36
Link to new issue: https://github.com/camunda-community-hub/camunda-cloud-helm/issues/153
Also found some new info: The elasticsearch index "operate-flownode-instance-1.3.0_" does not have any data stored from after the update. The activity stops exactly at the time of the update.
