### ISSUE TITLE
timeout large parameter zeebe monitor.

### ISSUE THREAD

**Issue by Javierleal** [camunda-cloud/zeebe#4825] opened 2020-06-25 20:04 UTC
**Describe the bug**
can help me to solve my question.

I am trying to send a base64 per parameter, the file is approximately 1.5Mb, although I have moved the configuration times in timeouts I still get the same error.

**To Reproduce**
It occurs exactly when I try to generate a new instance of my worker and send 3 parameters in the incidens layer it indicates the following error: failed to evaluate expression '{id: id, image: image, video: video}': no ​​variable found for name 'id' but I have already tried that service in my local and it works in problem happens when mounting it in the server.

**Log/Stacktrace**
failed to evaluate expression '{id:id,image:image,video:video}': no variable found for name 'id'

**Comment by Javierleal** [comment] 2020-06-26 13:24
I'd like to give a little more detail, is that I saw other things yesterday. 

One of those things is that the error that is issued when sending the parameter is Error: timeout but when going to the list of incidents the error that details is unrelated to the other detail that is important to reproduce this error is that I am working with the installation of zeebe on a server and testing the workers from my machine , 

this on-premises test works smoothly is only when the parameters are large must be moved to a server.

**Comment by saig0** [comment] 2020-07-06 05:41
Hi @Javierleal,

thank you for reporting. Currently, I'm not sure that is the issue and how to reproduce it. Please provide more information to continue with this issue.

* the version of the Zeebe broker and the environment that you're using
* the BPMN file that is deployed
* all commands that you're sending (e.g. using `zbctl`) in a step-by-step way

**Comment by npepinpe** [comment] 2021-06-15 08:57
As there was no other activity since almost a year, I will close this. Feel free to reopen if you still face this problem.

**Closed by npepinpe** 2021-06-15 08:57 UTC
Labels: Status: Needs Information, Type: Bug
