### ISSUE TITLE
Allow seeking to ASQN with an upper bound index

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6343] opened 2021-02-15 14:07 UTC
**Description**

`RaftLogReader#seekToAsqn` delegates the call to the `JournalReader#seekToAsqn`. Right now this is usually fine as we typically only seek to ASQNs which have been committed (since we don't process any record with a greater ASQN, and we only seek to it initially during recovery).

For the committed reader, however, we need to bound the seek to the commit index. We decided against keeping track of the committed ASQN as that would be expensive - you'd need to replicate it in the protocol, or read it back from the log as a follower, and need to keep track of it in several places.

`JournalReader#seekToAsqn(long)` should be changed to `JournalReader#seekToAsqn(long, long)`, with the second parameter being `upperBoundIndex`, which allows seeking to an ASQN with an upper bound index, such that:

- seek to a record with ASQN less than or equal to the given ASQN
- seek to a record with index less than or equal to the given upper bound index

The semantics of the new method should otherwise be the same as the previous `seekToAsqn(long)`.

Blocks #6307

**Comment by npepinpe** [comment] 2021-02-17 09:09
@MiguelPires let's do it after #6307 is merged - for now we'll just throw an exception if you seek to an uncommitted ASQN. This will help us get #6307 in faster, and then we can parallelize more work.

**Comment by deepthidevaki** [comment] 2021-03-24 12:50
Observed a `java.lang.UnsupportedOperationException: Cannot seek to an ASQN that is not yet committed ` in one of the benchmark cluster. This happened because of asynchronous role transitions in raft and streamprocessor. On the raft, it has already transitioned to follower meaning it has appened more uncommitted events. On the zeebe side, streamprocessor is still running which is executing `seekToEnd` resulting in this exception. 

Our assumption that this would not happen is not valid because of the asynchronous role transitions. We should either fix this - implement a proper seekToEnd method, or handle this exception so that the broker wouldn't crash.

**Comment by npepinpe** [comment] 2021-03-24 12:51
The proposed solution should be easy to implement no?

**Comment by deepthidevaki** [comment] 2021-03-24 12:54
> The proposed solution should be easy to implement no?

I think so. I haven't thought much about it.

**Comment by npepinpe** [comment] 2021-03-24 21:45
Hm, is this related to https://github.com/camunda-cloud/zeebe/issues/5517 then?

**Comment by deepthidevaki** [comment] 2021-03-25 06:53
> Hm, is this related to #5517 then?

I don't think so. But both are caused by asynchronous role transitions.

**Comment by npepinpe** [comment] 2021-03-25 07:08
Sorry yes, this is what I meant :sweat_smile:

**Closed** 2021-04-01 07:46 UTC
Labels: Impact: Tech Debt, Scope: broker, Status: Needs Review, Type: Maintenance
