### ISSUE TITLE
NPE in ProcessInstanceSequenceFlowTakenApplier during Replay

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7864] opened 2021-09-20 11:45 UTC
**Describe the bug**

Might be related to https://github.com/camunda-cloud/zeebe/issues/7862 but not 100% clear, need to be investigated further.

Impact: Processor fails, because we don't expect any exceptions to be thrown on replay.

```
2021-09-17 13:23:32.968 CEST
zeebe-3
Broker-3-StreamProcessor-74
Actor Broker-3-StreamProcessor-74 failed in phase STARTED.
```
[
We can see earlier that the log stream readers are closed for that partition.](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:23:33.139016000Z&dateRangeStart=2021-09-17T10:24:08.460Z&dateRangeEnd=2021-09-17T12:24:08.460Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:23:32.516981000Z&pinnedLogId=jfmsq1dqg8e6zfuj&pinnedLogTimestamp=2021-09-17T11:23:32.473328Z)

```

2021-09-17 13:23:32.473 CEST
zeebe-3
Broker-3-LogStream-74
On closing logstream logstream-raft-partition-partition-74 close 2 readers
```

Error Groups:

 * https://console.cloud.google.com/errors/CPWisMW3k7jQtgE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: java.lang.NullPointerException
at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$4 (ReplayStateMachine.java:162)
at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run (FutureContinuationRunnable.java:33)
at io.camunda.zeebe.util.sched.ActorJob.invoke (ActorJob.java:76)
at io.camunda.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
at io.camunda.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:94)
at io.camunda.zeebe.util.sched.ActorThread.doWork (ActorThread.java:78)
at io.camunda.zeebe.util.sched.ActorThread.run (ActorThread.java:191)
Caused by: java.lang.NullPointerException
at io.camunda.zeebe.engine.state.appliers.ProcessInstanceSequenceFlowTakenApplier.applyState (ProcessInstanceSequenceFlowTakenApplier.java:44)
at io.camunda.zeebe.engine.state.appliers.ProcessInstanceSequenceFlowTakenApplier.applyState (ProcessInstanceSequenceFlowTakenApplier.java:19)
at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState (EventAppliers.java:250)
at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.applyCurrentEvent (ReplayStateMachine.java:290)
at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.replayEvent (ReplayStateMachine.java:219)
at java.util.Iterator.forEachRemaining (Unknown Source)
at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$tryToReplayBatch$5 (ReplayStateMachine.java:200)
at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run (ZeebeTransaction.java:84)
at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.tryToReplayBatch (ReplayStateMachine.java:198)
at io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$3 (ReplayStateMachine.java:158)
at io.camunda.zeebe.util.retry.ActorRetryMechanism.run (ActorRetryMechanism.java:36)
at io.camunda.zeebe.util.retry.RecoverableRetryStrategy.run (RecoverableRetryStrategy.java:47)
at io.camunda.zeebe.util.sched.ActorJob.invoke (ActorJob.java:73)
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-alpha2
 - Configuration:

**Comment by Zelldon** [comment] 2021-09-20 12:05
It seems to happen on a different partition but looks like the same sequence, reader are getting closed and the replay fails of a certain instance.

https://console.cloud.google.com/errors/COC15KXI4c2ESQ?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

Sequence:

1. [Appending fails](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:23:36.189970000Z&dateRangeStart=2021-09-17T10:24:06.189Z&dateRangeEnd=2021-09-17T12:24:06.189Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:23:29.006606000Z&pinnedLogId=cqdi6c6pqjssvzg8&pinnedLogTimestamp=2021-09-17T11:23:29.006606Z)
2. [LogStream is closed](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:23:36.189970000Z&dateRangeStart=2021-09-17T10:24:06.189Z&dateRangeEnd=2021-09-17T12:24:06.189Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:23:29.084499000Z&pinnedLogId=8agj7hcpp4fa27sz&pinnedLogTimestamp=2021-09-17T11:23:29.084499Z)
3. [StreamProcessor fails](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:23:36.189970000Z&dateRangeStart=2021-09-17T10:24:06.189Z&dateRangeEnd=2021-09-17T12:24:06.189Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:23:29.170403000Z&pinnedLogId=yqvpid2sga7xjsrk&pinnedLogTimestamp=2021-09-17T11:23:29.120839Z)

**Comment by npepinpe** [comment] 2021-09-21 07:57
Assumption is snapshot was corrupted due to https://github.com/camunda-cloud/zeebe/issues/7856

**Comment by Zelldon** [comment] 2021-09-24 08:06
I assume we can close this then as well @deepthidevaki @npepinpe

**Comment by deepthidevaki** [comment] 2021-09-24 08:22
Assuming #7856 is the cause, yes. If "appending fails due to position mismatch" is the cause, we have another issue open for it. So we can close this.

**Closed by deepthidevaki** 2021-09-24 08:22 UTC
Labels: Type: Bug, Scope: broker, Severity: High
