### ISSUE TITLE
Failed to convert JSON variables to MessagePack

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#7187] opened 2021-06-03 15:18 UTC
**Describe the bug**
Failure to convert the JSON variables to message pack. I've only seen this once and didn't find anything else weird in the logs, so maybe the variables were just initially malformed or corrupted in-transit. 

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Failed to convert JSON to MessagePack
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:80) ~[zeebe-protocol-impl-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:71) ~[zeebe-protocol-impl-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.gateway.RequestMapper.ensureJsonSet(RequestMapper.java:157) ~[zeebe-gateway-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.gateway.RequestMapper.toPublishMessageRequest(RequestMapper.java:61) ~[zeebe-gateway-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.gateway.EndpointManager.sendRequest(EndpointManager.java:306) [zeebe-gateway-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.gateway.EndpointManager.publishMessage(EndpointManager.java:221) [zeebe-gateway-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.gateway.GatewayGrpcService.publishMessage(GatewayGrpcService.java:112) [zeebe-gateway-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.gateway.protocol.GatewayGrpc$MethodHandlers.invoke(GatewayGrpc.java:1503) [zeebe-gateway-protocol-impl-1.0.0.jar:1.0.0]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [grpc-stub-1.37.0.jar:1.37.0]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [grpc-api-1.37.0.jar:1.37.0]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [grpc-api-1.37.0.jar:1.37.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [grpc-core-1.37.0.jar:1.37.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797) [grpc-core-1.37.0.jar:1.37.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.37.0.jar:1.37.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.37.0.jar:1.37.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in field name
 at [Source: (ByteArrayInputStream); line: 1, column: 14]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:662) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseEscapedName(UTF8StreamJsonParser.java:2020) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.slowParseName(UTF8StreamJsonParser.java:1925) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1709) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:766) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.JsonGenerator._copyCurrentContents(JsonGenerator.java:2513) ~[jackson-core-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:2494) ~[jackson-core-2.12.3.jar:2.12.3]
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convert(MsgPackConverter.java:136) ~[zeebe-protocol-impl-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.protocol.impl.encoding.MsgPackConverter.convertToMsgPack(MsgPackConverter.java:76) ~[zeebe-protocol-impl-1.0.0.jar:1.0.0]
	... 17 more
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.0.0
 - Configuration:

**Comment by npepinpe** [comment] 2021-06-04 07:40
Duplicate of #7025

**Closed by npepinpe** 2021-06-04 07:40 UTC
Labels: Type: Bug
