### ISSUE TITLE
TestZbctlWithInsecureGateway/TestCommonCommands/deploy_workflow unstable

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#5696] opened 2020-10-27 08:29 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? From time to time
- Does it block your work? Not yet
- Do we suspect that it is a real failure? Yes

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>

[2020-10-27T06:43:46.062Z] + .ci/scripts/distribution/test-go.sh

[2020-10-27T06:43:46.062Z] + ORG_DIR=/go/src/github.com/zeebe-io

[2020-10-27T06:43:46.062Z] + cd /go/src/github.com/zeebe-io/zeebe/clients/go

[2020-10-27T06:43:46.062Z] + gotestsum --raw-command --junitfile TEST-go.xml go test -mod=vendor -v -json ./...

[2020-10-27T06:44:12.859Z] ✓  pkg/entities (26ms)

[2020-10-27T06:44:12.860Z] ✓  internal/utils (8ms)

[2020-10-27T06:44:12.860Z] ✓  pkg/commands (27ms)

[2020-10-27T06:44:12.860Z] ✓  pkg/worker (322ms)

[2020-10-27T06:44:12.860Z] ✓  pkg/zbc (179ms)

[2020-10-27T06:44:34.869Z] ✓  test (21.11s)

[2020-10-27T06:46:26.490Z] ✖  cmd/zbctl (2m7.53s)

[2020-10-27T06:46:26.490Z] ∅  cmd/zbctl/internal/commands

[2020-10-27T06:46:26.490Z] ∅  internal/containersuite

[2020-10-27T06:46:26.490Z] ∅  internal/embedded

[2020-10-27T06:46:26.490Z] ∅  internal/mock_pb

[2020-10-27T06:46:26.490Z] ∅  pkg/pb

[2020-10-27T06:46:26.490Z] 

[2020-10-27T06:46:26.490Z] === Failed

[2020-10-27T06:46:26.490Z] === FAIL: cmd/zbctl TestZbctlWithInsecureGateway/TestCommonCommands/deploy_workflow (5.00s)

[2020-10-27T06:46:26.491Z]         --- FAIL: TestZbctlWithInsecureGateway/TestCommonCommands/deploy_workflow (5.00s)

[2020-10-27T06:46:26.491Z]             main_test.go:143: deploy workflow: diff (-want +got):

[2020-10-27T06:46:26.491Z]                   []string{

[2020-10-27T06:46:26.491Z]                 - 	"{",

[2020-10-27T06:46:26.491Z]                 - 	`  "key": 2251799813685250,`,

[2020-10-27T06:46:26.491Z]                 - 	`  "workflows": [`,

[2020-10-27T06:46:26.491Z]                 - 	"    {",

[2020-10-27T06:46:26.491Z]                 - 	`      "bpmnProcessId": "process",`,

[2020-10-27T06:46:26.491Z]                 - 	`      "version": 1,`,

[2020-10-27T06:46:26.491Z]                 - 	`      "workflowKey": 2251799813685345,`,

[2020-10-27T06:46:26.491Z]                 - 	`      "resourceName": "model.bpmn"`,

[2020-10-27T06:46:26.491Z]                 - 	"    },",

[2020-10-27T06:46:26.491Z]                 - 	"    {",

[2020-10-27T06:46:26.491Z]                 - 	`      "bpmnProcessId": "jobProcess",`,

[2020-10-27T06:46:26.491Z]                 - 	`      "version": 1,`,

[2020-10-27T06:46:26.491Z]                 - 	`      "workflowKey": 2251799813685346,`,

[2020-10-27T06:46:26.491Z]                 - 	`      "resourceName": "job.bpmn"`,

[2020-10-27T06:46:26.491Z]                 - 	"    }",

[2020-10-27T06:46:26.491Z]                 - 	"  ]",

[2020-10-27T06:46:26.491Z]                 - 	"}",

[2020-10-27T06:46:26.491Z]                   	... // 1 identical element

[2020-10-27T06:46:26.491Z]                   }

[2020-10-27T06:46:26.491Z] 

[2020-10-27T06:46:26.491Z] === FAIL: cmd/zbctl TestZbctlWithInsecureGateway/TestCommonCommands (14.60s)

[2020-10-27T06:46:26.491Z]     --- FAIL: TestZbctlWithInsecureGateway/TestCommonCommands (14.60s)

[2020-10-27T06:46:26.491Z] 

[2020-10-27T06:46:26.491Z] === FAIL: cmd/zbctl TestZbctlWithInsecureGateway (127.49s)

[2020-10-27T06:46:26.491Z] 2020/10/27 06:45:35 Starting container id: 972b8ca59345 image: quay.io/testcontainers/ryuk:0.2.3

[2020-10-27T06:46:26.491Z] 2020/10/27 06:45:36 Waiting for container id 972b8ca59345 image: quay.io/testcontainers/ryuk:0.2.3

[2020-10-27T06:46:26.491Z] 2020/10/27 06:45:36 Container is ready id: 972b8ca59345 image: quay.io/testcontainers/ryuk:0.2.3

[2020-10-27T06:46:26.491Z] 2020/10/27 06:45:36 Starting container id: e7296b46deef image: camunda/zeebe:current-test

[2020-10-27T06:46:26.491Z] 2020/10/27 06:45:37 Waiting for container id e7296b46deef image: camunda/zeebe:current-test

[2020-10-27T06:46:26.491Z] 2020/10/27 06:46:04 Container is ready id: e7296b46deef image: camunda/zeebe:current-test

[2020-10-27T06:46:26.491Z] 

[2020-10-27T06:46:26.491Z] 

[2020-10-27T06:46:26.491Z] DONE 168 tests, 3 failures in 154.438s
</pre>
</details>
Failing build https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/PR-5691/1/pipeline

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

Might be two issue's. One with the go client that it doesn't return any result when an error/rejection is returned and that the broker doesn't accept the deployment.

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by npepinpe** [comment] 2020-10-29 13:22
Seen it happen again https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/develop/4500/tests

**Comment by MiguelPires** [comment] 2021-06-08 17:59
I ran the integration tests for a while but couldn't reproduce this. The test log is gone from the CI so it's hard to tell what happened. Looking at the tests I also didn't see any obvious reasons why it would be flaky. Since this is low priority and it's not clear whether this is still flaky or not, maybe we can close it for know and re-open with the logs if it happens again.

**Comment by npepinpe** [comment] 2021-06-08 18:10
Let's do that then :+1:

**Closed by npepinpe** 2021-06-08 18:10 UTC
Labels: Scope: clients/go, Type: Unstable Test
