### ISSUE TITLE
Unable to add resource to classpath using Zeebe with Quarkus

### ISSUE THREAD

**Issue by sterlingwellscaffeine** [camunda-cloud/zeebe#6040] opened 2020-12-23 17:55 UTC
**Describe the bug**
Unable to resolve any resources from addResourceFromClasspath method while building in dev mode with Quarkus

**To Reproduce**
1.) Create a quickstart Quarkus application using the following code:

- ```mvn io.quarkus:quarkus-maven-plugin:1.10.2.Final:create -DprojectGroupId="com.your.project"
        -DprojectArtifactId=zeebe-quarkus -DprojectVersion=1.0.0-SNAPSHOT -DclassName="com.your.project.YourApplication" -Dextensions="resteasy-jackson" -DbuildTool=gradle```

Then, proceed to create a bean to instantiate the zeebe java client.

Next attempt to deploy a bpmn using 

```client.newDeployCommand().addResourceFromClasspath("yourResource").send().join()```

2.) Attach the following 

**Expected behavior**
Should be able to resolve resource file from classPath

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

``` Cannot deploy resource from classpath. demo.bpmn
io.zeebe.client.impl.command.DeployWorkflowCommandImpl.addResourceFromClasspath(DeployWorkflowCommandImpl.java:122)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:60)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:81)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:598)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:96)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.FileNotFoundException: /META-INF/resources/orderProcess.bpmn
	at aio.zeebe.client.impl.command.DeployWorkflowCommandImpl.addResourceFromClasspath(DeployWorkflowCommandImpl.java:116)
	... 22 more
```

</p>
</details>

**Environment:**
 - OS: Windows 10
 - Zeebe Version: [e.g. 0.26.0-rc1]
 - Configuration: [e.g. exporters etc.]

** RCA ** 
According to [Quarkus](https://quarkus.io/guides/class-loading-reference), Zeebe should be getting the correct ClassLoader via `Thread.currentThread().getContextClassLoader()` method (which in this case would return the correct ClassLoader: `QuarkusRuntimeClassloader`. 

Zeebe is getting the classloader via `getClass().getClassLoader()` which returns the wrong classloader (`QuarkusBaseRuntimeClassloader`). 

** To Fix ** 
In order to make Zeebe compatible with Quarkus, the `DeployWorkflowCommandImpl` will have to be changed to use the following logic above to get the classloader.

**Comment by rezanirumand** [comment] 2021-01-04 08:56
Hi, 
This is documented in quarkus webstie: https://quarkus.io/guides/writing-native-applications-tips

See seection: Including resources

Best Regards

**Comment by saig0** [comment] 2021-01-05 05:08
@rezanirumand thanks for sharing :+1: 

So, is this a configuration issue in the application that uses the Zeebe client?
Or, do we still need to change the classloader to `Thread.currentThread().getContextClassLoader()`?

> The Quarkus class loading architecture is slightly different depending on the mode that the application is run in. When running a production application everything is loaded in the system ClassLoader, so it is a completely flat class path. This also applies to native image mode which does not really support multiple ClassLoaders, and is based on a normal production Quarkus application.
For all other use cases (e.g. tests, dev mode, and building the application) Quarkus uses the class loading architecture outlined here. [...]

It sounds like that it should work in production mode because it uses the system classloader. Correct?

**Comment by saig0** [comment] 2021-01-06 05:49
@sterlingwellscaffeine please verify this issue again. It seems to work for @nirumand.

> Have you managed to build a native image with zeebe?

We didn't try yet. Currently, this is not our focus. However, I see value in supporting it. We're open to contributions :)

**Comment by npepinpe** [comment] 2021-07-14 14:01
@nirumand - here's an example for 0.26 - https://github.com/npepinpe/zeebe-quarkus-example. I haven't updated it to 1.0 so it might be missing some thing, but it could already serve as a base.

As for the issue itself, I will close it for now. It seems we don't need to use the TCL explicitly. Reading the Quarkus docs, the reference to the TCL seems to be explicitly about reading class byte code, not resources. As another user confirmed the code above worked without the TCL, I would leave it as is for now.

**Closed by npepinpe** 2021-07-14 14:01 UTC
Labels: Impact: Integration, Scope: clients/java, Severity: Mid, Type: Bug

**Comment by andrejpetras** [comment] 2021-11-09 08:15
@sterlingwellscaffeine @npepinpe @nirumand @saig0 
Hi, this could be interesting for you. We have just finished the `quarkus-zeebe` extension with native-image support.
https://github.com/quarkiverse/quarkus-zeebe
