### ISSUE TITLE
Empty log statements in stack driver

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6944] opened 2021-05-03 13:34 UTC
**Describe the bug**

It seems that we somehow write empty log statements:

```
D 2021-05-03T13:24:36.286969Z Created segment: JournalSegment{id=29, index=546208} 
D 2021-05-03T13:24:36.292589Z Created segment: JournalSegment{id=29, index=546208} 
I 2021-05-03T13:24:38.868959420Z {} 
I 2021-05-03T13:24:40.706146138Z {} 
I 2021-05-03T13:24:44.250664226Z {} 
D 2021-05-03T13:24:44.549775Z Created segment: JournalSegment{id=30, index=558673} 
D 2021-05-03T13:24:44.552736Z Created segment: JournalSegment{id=30, index=558673} 
D 2021-05-03T13:24:44.554953Z Created segment: JournalSegment{id=30, index=558673} 
```

There is no much detail I can give here, it is just unexpected.
```
{
 insertId: "116qzxdg3j33nol"  
 jsonPayload: {
 }
 labels: {
  compute.googleapis.com/resource_name: "gke-ultrachaos-pvm-n1-standard-16-cacf25f4-58lc"   
  k8s-pod/app_kubernetes_io/app: "zeebe"   
  k8s-pod/app_kubernetes_io/component: "gateway"   
  k8s-pod/controller-revision-hash: "zeebe-754ddc64d"   
  k8s-pod/statefulset_kubernetes_io/pod-name: "zeebe-4"   
 }
 logName: "projects/camunda-cloud-240911/logs/stdout"  
 receiveTimestamp: "2021-05-03T13:24:40.192148680Z"  
 resource: {
  labels: {
   cluster_name: "ultrachaos"    
   container_name: "zeebe"    
   location: "europe-west1-d"    
   namespace_name: "de990736-75b6-4e2b-8b51-65b2ccd9174d-zeebe"    
   pod_name: "zeebe-4"    
   project_id: "camunda-cloud-240911"    
  }
  type: "k8s_container"   
 }
 severity: "INFO"  
 timestamp: "2021-05-03T13:24:38.868959420Z"  
}
```

**To Reproduce**
Use alpha channel and create alpha 7 cluster

**Expected behavior**

No empty Logs:

**Environment:**
 - OS: camunda cloud - prod l - alpha 7

**Comment by npepinpe** [comment] 2021-05-03 13:56
The last changes we did recently were with the removal of deprecated things - do we think this could have had any effect whatsoever? :thinking:

**Comment by Zelldon** [comment] 2021-05-03 17:10
Not sure I wouldnt expect that this cause something like this

**Comment by npepinpe** [comment] 2021-05-04 09:05
Looking into it, and I can't think of a way for our application to have a completely empty jsonPayload. If you log `LOGGER.info("")`, you will get some fields in the JSON payload - just no message. 

The only way I managed to reproduce it is by printing `''` to the STDOUT of the process - then you get an empty JSON payload. This could mean that log4j2 is somehow printing extra new lines or some such - but I don't think there's anything wrong with our layout itself. You can reproduce this by running `echo '' > /proc/7/fd/1` (where 7 is the PID of your process) in one of the brokers, and you will get an empty log statement.

My assumption would be extra new lines from log4j2, or something weird going on with the async appenders because we're flooding the logs with deprecated warnings. I don't think we're losing information, so as such, I will downgrade this.

**Comment by Zelldon** [comment] 2021-06-30 05:48
I have seen this again today, when looking into 1.1.0-alpha1 cluster

```
D 2021-06-30T02:32:33.888054Z Open exporter with id 'MetricsExporter' 
I 2021-06-30T02:32:33.888648392Z {} 
D 2021-06-30T02:32:34.052762Z Received metadata change from Broker 0, partitions {1=LEADER, 2=LEADER}, terms {1=2, 2=2} and health {1=HEALTHY, 2=HEALTHY}. 
D 2021-06-30T02:32:34.054207Z Received metadata change from Broker 0, partitions {1=LEADER, 2=LEADER}, terms {1=2, 2=2} and health {1=HEALTHY, 2=HEALTHY}. 
D 2021-06-30T02:32:34.054265Z Received metadata change for 0, partitions {1=LEADER, 2=LEADER} terms {1=2, 2=2} 
D 2021-06-30T02:32:34.054674Z Received metadata change from Broker 0, partitions {1=LEADER, 2=LEADER}, terms {1=2, 2=2} and health {1=HEALTHY, 2=HEALTHY}. 
I 2021-06-30T02:32:34.054934154Z {} 
```
https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-06-30T03:14:58.497000000Z&dateRangeStart=2021-06-30T02:14:58.497Z&dateRangeEnd=2021-06-30T04:14:58.497Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%227e15d65f-c03c-4b36-b540-c22b89d5ea7c-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-06-30T03:05:33.918218000Z&pinnedLogId=1mjrle7g4s1mlft&pinnedLogTimestamp=2021-06-30T02:32:33.888648392Z

**Comment by npepinpe** [comment] 2021-07-14 13:31
As I mentioned, I don't think we're losing any information here. I wouldn't invest more time here unless we had new knowledge, i.e. we suspect we are losing some log statements (but afaik this isn't the case). I would close this for now, but please challenge this if you think otherwise.

**Closed by npepinpe** 2021-07-14 13:31 UTC
Labels: Impact: Observability, Scope: broker, Type: Bug
