### ISSUE TITLE
JVM crashs in CI Builds

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7841] opened 2021-09-17 06:08 UTC
**Description**

It seems that we have again some SIGSEG issues, which causes to crash the JVM in our CI.

It downloaded the test errors zip from the following build https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/develop/821/ 
```
$ unzip test-errors-it.zip 
Archive:  test-errors-it.zip
  inflating: qa/integration-tests/hs_err_pid6859.log  
  inflating: qa/integration-tests/hs_err_pid6860.log  
$ cd qa/integration-tests/
$ ll
total 8
-rw-r--r-- 1 zell users 3144 Sep 16 15:13 hs_err_pid6859.log
-rw-r--r-- 1 zell users  396 Sep 16 15:10 hs_err_pid6860.log
$ cat hs_err_pid6860.log 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1975573435, pid=6860, tid=57545
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.10+9) (build 11.0.10+9)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.10+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [librocksdbjni4887027544215651946.so+0x395435][zell integration-tests/ cluster: tf-jx-precise-humpback ns:jx]$ 
```

```
$ cat hs_err_pid6859.log 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8e41d86821, pid=6859, tid=61320
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.10+9) (build 11.0.10+9)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.10+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x82821]
[timeout occurred during error reporting in step "printing problematic frame"] after 30 s.
# Core dump will be written. Default location: /core.%e.6859.%t
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -XX:+UseContainerSupport -XX:MaxRAMPercentage=8 -XX:MaxDirectMemorySize=4g -Djava.net.preferIPv4Stack=true --module-path=/home/jenkins/agent/workspace/camunda-cloud_zeebe_develop/qa/integration-tests/target/zeebe-qa-integration-tests-1.2.0-SNAPSHOT.jar --patch-module=zeebe.qa.integration.tests=/home/jenkins/agent/workspace/camunda-cloud_zeebe_develop/qa/integration-tests/target/test-classes --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.client=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.client.command=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.client.multipartition=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.clustering=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.clustering.topology=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.gateway=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.health=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.network=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.smoke=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.startup=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.system=ALL-UNNAMED --add-modules=zeebe.qa.integration.tests --add-reads=zeebe.qa.integration.tests=ALL-UNNAMED org.apache.maven.surefire.booter.ForkedBooter /home/jenkins/agent/workspace/camunda-cloud_zeebe_develop/qa/integration-tests/target/surefire 2021-09-16T15-01-45_695-jvmRun1 surefire7038759527328167887tmp surefire_115532971887761201284tmp

Host: 
[timeout occurred during error reporting in step "printing summary machine and OS info"] after 30 s.
Time: Thu Sep 16 15:12:57 2021 UTC elapsed time: 401.604736 seconds (0d 0h 6m 41s)

---------------  T H R E A D  ---------------

Current thread (0x00007f8c4420c800):  JavaThread "Broker-2-zb-fs-workers-0" daemon [_thread_in_native, id=61320, stack(0x00007f8c07cbb000,0x00007f8c07dbc000)]

Stack: [0x00007f8c07cbb000,0x00007f8c07dbc000],  sp=0x00007f8c07db88b0,  free space=1014k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x82821]
------ Timeout during error reporting after 120 s. ------
```

[test-errors-it.zip](https://github.com/camunda-cloud/zeebe/files/7183048/test-errors-it.zip)

**Comment by Zelldon** [comment] 2021-09-17 07:52
There is another reason why build fails, because of oom. https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/staging/1072/


```

[2021-09-17T07:15:52.183Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ zeebe-qa-update-tests ---

[2021-09-17T07:16:04.608Z] [ERROR] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f36ccaf5000, 16384, 0) failed; error='Not enough space' (errno=12)
[2021-09-17T07:16:04.608Z] [ERROR] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memoOpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007ff710503000, 65536, 1) failed; error='Not enough space' (errno=12)
[2021-09-17T07:16:04.608Z] ry(0x00007f87006f0000, 16384, 0) failed; error='Not enough space' (errno=12)
[2021-09-17T07:16:04.608Z] #
[2021-09-17T07:16:04.608Z] # There is insufficient memory for the Java Runtime Environment to continue.
[2021-09-17T07:16:04.608Z] # Native memory allocation (mmap) failed to map 65536 bytes for committing reserved memory.
[2021-09-17T07:16:04.608Z] # An error report file with more information is saved as:
[2021-09-17T07:16:04.608Z] # /home/jenkins/agent/workspace/camunda-cloud_zeebe_staging/hs_err_pid1384.log
[2021-09-17T07:16:04.608Z] #
[2021-09-17T07:16:04.608Z] # Compiler replay data is saved as:
[2021-09-17T07:16:04.608Z] # /home/jenkins/agent/workspace/camunda-cloud_zeebe_staging/replay_pid1384.log
[2021-09-17T07:16:04.608Z] + status=1
[2021-09-17T07:16:04.608Z] + analyseFlakyTests /tmp/tmp.aDJbOpA8qk ./FlakyTests.txt
[2021-09-17T07:16:04.608Z] + local -r testInputFile=/tmp/tmp.aDJbOpA8qk
[2021-09-17T07:16:04.608Z] + local -r testOutputFile=./FlakyTests.txt
[2021-09-17T07:16:04.608Z] ++ mktemp
[2021-09-17T07:16:04.608Z] + local -r irOutputFile=/tmp/tmp.bOIlTaeXyT
[2021-09-17T07:16:04.608Z] + grep -q '\[WARNING\] Flakes:' /tmp/tmp.aDJbOpA8qk
[2021-09-17T07:16:04.608Z] + return 0
[2021-09-17T07:16:04.608Z] + [[ 1 != 0 ]]
```

[test-errors-it (1).zip](https://github.com/camunda-cloud/zeebe/files/7183727/test-errors-it.1.zip)

The hs_error logs show more details.

**Comment by npepinpe** [comment] 2021-09-17 08:00
Looking at the value (65536), it looks like the standard ulimit value? So we might be busting that :thinking:

**Comment by npepinpe** [comment] 2021-09-17 08:03
Hm, never mind, it seems it's already unlimited :sweat_smile:

**Comment by npepinpe** [comment] 2021-09-17 08:27
Ah, it might be the maven container is running out of memory. We allocate 48GB, but it looks like it's getting up there. It seems on the DIND side we barely use memory, so we could lower than ratio and give more to the maven one. It still never reaches 48GB according to Google Cloud though...and I would expect the OOM killer to kill it before it crashes, but... :man_shrugging:

**Comment by Zelldon** [comment] 2021-09-17 08:28
Maybe a leak during the test executions?

**Comment by npepinpe** [comment] 2021-09-17 08:29
As a temporary measure, feel free to change the memory of the containers - there's 108GB to split across both, so we could do a split of 78GB for maven, 30GB for dind - it looks like the dind one only really uses 10GB at most, but just to be safe we can keep a bit more.

**Comment by npepinpe** [comment] 2021-09-17 08:30
Yeah that's also possible, it's happened in the past. I guess this would be reproduceable locally, I can look into it next week.

**Comment by Zelldon** [comment] 2021-09-17 13:31
I think one of our issues is that we have open actor schedulers lying around

![schedulers](https://user-images.githubusercontent.com/2758593/133790739-a028b7b0-5ec9-450d-9716-57d14b5a6c9b.png)

This causes to many thread to be alive

![threads](https://user-images.githubusercontent.com/2758593/133790804-97f679b2-950d-4403-ab48-18ac6364d1cb.png)
![test](https://user-images.githubusercontent.com/2758593/133790806-21047df8-5f72-4ff0-a3bb-0569897b9fb1.png)

This can cause then going out of native memory if we create to many threads

**Comment by npepinpe** [comment] 2021-09-17 13:40
Good catch! Yes, the actor scheduler by default schedules as many threads as there are cores, which on CI will go up very quickly :smile:

**Comment by Zelldon** [comment] 2021-09-17 13:42
I already have an fix.

**Comment by npepinpe** [comment] 2021-09-17 13:42
We recently added tests which use `ActorScheduler` instances related to the query api stuff, maybe it's that?

**Comment by Zelldon** [comment] 2021-09-17 13:42
No it is about the clustering rule and starting the actor scheduler outside and stopping outside the broker..

**Comment by Zelldon** [comment] 2021-09-17 13:44
Related to this PR https://github.com/camunda-cloud/zeebe/pull/7783

**Comment by Zelldon** [comment] 2021-09-17 16:49
We should take a look at it again

**Comment by npepinpe** [comment] 2021-09-21 14:17
Looking at the latest crash logs, it seems related to the snapshot director trying to take a snapshot after we've closed ZeebeDb. Which is strange, since in the transition we close the director first. Digging into it, it looks like we close the DB while we're in the process of taking a snapshot. In short, closing the actor doesn't interrupt the ongoing job since that job runs on the snapshot store actor :smile: 

It would make sense to run the actual snapshot taking operation on the director, I think, since it is the one in charge of taking the snapshot. Since we're dealing with pending snapshots, I think it's safe to not have it synchronized via the snapshot store, so long as the commit operation is synchronized there.

**Comment by npepinpe** [comment] 2021-09-22 08:35
Closing in favor of https://github.com/camunda-cloud/zeebe/issues/7889

**Closed by npepinpe** 2021-09-22 08:35 UTC
Labels: Type: Maintenance
