### ISSUE TITLE
ResourceExhausted constantly appears during workflow deployment

### ISSUE THREAD

**Issue by IcyEagle** [camunda-cloud/zeebe#3367] opened 2019-11-14 12:12 UTC
Hi there!

I use one of the latest version of Zeebe under the hook (took a snapshot after 0.21.1).

Since this morning I have had an error **ResourceExhausted** when I try to upload an updated workflow. It's reproduced stably. It's strange since I have no load on my 5-nodes cluster. I have some workers connected but there are no active instances.

Here is my config:
```
    # For more information about this configuration visit:
    [threads]
    cpuThreadCount = 40

    [gateway.monitoring]
    enabled = true

    [network]
    host = "0.0.0.0"

    [[exporters]]
    id = "log"
    className = "org.projectx.LogExporter"

    [exporters.args]
    enabledValueTypes = "JOB,WORKFLOW_INSTANCE,DEPLOYMENT,INCIDENT,TIMER,VARIABLE,MESSAGE,MESSAGE_SUBSCRIPTION,MESSAGE_START_EVENT_SUBSCRIPTION"
```

Here is the command:
```ls -d $dpmn_sources_dir/* | xargs /usr/local/zeebe/bin/zbctl --certPath ca-cert --address $ZEEBE_HOST deploy```

and here is the result: 
```Error: rpc error: code = ResourceExhausted desc = Reached maximum capacity of requests handled```

How can I deal with it?

One more thing about performance: how is it better to monitor Zeebe cluster state in production environment? I have Zeebe metrics active + Prometeus/Grafana connected. Is it enough in general? Is there a guide somewhere maybe? :)

Thanks!

**Comment by npepinpe** [comment] 2019-11-14 12:24
Hey there, thanks for reporting this. `ResourceExhausted` is returned when there is backpressure from the broker, which can happen not only on sustained high load but on bursts. There is an issue to investigate handling bursts of traffic gracefully, [see here](https://github.com/zeebe-io/zeebe/issues/3137#issuecomment-553415001).

From the metrics you should be able to get some idea of the current load, and some backpressure related metrics will give you an idea how much the system can currently tolerate. Here's a panel JSON for Grafana from our dashboard (you might have to edit it a bit for yours):

<details><summary>Command API Panel JSON</summary>
<p>

```json
{
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "fill": 1,
  "fillGradient": 0,
  "gridPos": {
    "h": 8,
    "w": 12,
    "x": 12,
    "y": 48
  },
  "id": 31,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "null",
  "options": {
    "dataLinks": []
  },
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "expr": "sum(rate(zeebe_dropped_request_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
      "format": "time_series",
      "intervalFactor": 1,
      "legendFormat": "dropped-{{partition}}",
      "refId": "A"
    },
    {
      "expr": "sum(rate(zeebe_received_request_count_total{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (partition)",
      "format": "time_series",
      "intervalFactor": 1,
      "legendFormat": "received-{{partition}}",
      "refId": "B"
    },
    {
      "expr": "sum(zeebe_backpressure_requests_limit{namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}) by (partition)",
      "format": "time_series",
      "intervalFactor": 1,
      "legendFormat": "queue-limit-{{partition}}",
      "refId": "C"
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeRegions": [],
  "timeShift": null,
  "title": "Command API Backpressure",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}
```

</p></details>

> One more thing about performance: how is it better to monitor Zeebe cluster state in production environment?

There is a guide still in the works, but I don't think it has been published yet. There's a PR in the works to add some distributed tracing so that will help as well (#3341), but for now it's pretty much only metrics and logs.

**Comment by jwulf** [comment] 2019-11-14 12:37
I observe this on a cluster deployed using the zeebe-helm charts with zero load.

I use the Node client, which retries automatically. It works on the second attempt, so I've been ignoring it.

**Comment by npepinpe** [comment] 2019-11-14 12:39
It's possibly tied to the following issue as well #3364, which can result in the gateway sending requests to the same shrinking set of brokers over time, resulting in higher load on a single partition/broker.

**Comment by IcyEagle** [comment] 2019-11-14 13:31
> It's possibly tied to the following issue as well #3364, which can result in the gateway sending requests to the same shrinking set of brokers over time, resulting in higher load on a single partition/broker.

Curiously. I have a very similar issue once a day. For some reason, one of my partitions drops out of the operation on a single node and can't be restored. It leads to high network IO activity on both the leader node and the node with the broken partition. I checked likely everything (pod resources, jvm resources, some Zeebe metrics) and didn't find the reason so I just restart the node and the problem disappears for some time. Not a production solution...

Unfortunately, I'm not experienced in Atomix operation details and can't realize where is the root cause.

**Comment by npepinpe** [comment] 2019-11-14 13:40
What do you mean by:

> one of my partitions drops out of the operation on a single node and can't be restored

Meaning it stops processing, or do you see exceptions, or was there a network partition, etc. And by restored, you mean the restore operation (i.e. the logs say it's currently restoring up to position X)?

**Comment by IcyEagle** [comment] 2019-11-20 10:56
@npepinpe sorry for the delay.

Yeah, it seems like I have a very similar problem after failover.
In a few days, it happened again with the message on the failed node:

`Failed to receive deployment response for partitions [3] (topic 'deployment-response-2251799813983750`

and I have the third partition lost:
```
Cluster size: 5
Partitions count: 3
Replication factor: 5
Brokers:
  Broker 0 - zeebe-cluster-0.zeebe-cluster.svc.cluster.local:26501
    Partition 1 : Follower
    Partition 2 : Leader
    Partition 3 : Follower
  Broker 1 - zeebe-cluster-1.zeebe-cluster.svc.cluster.local:26501
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
  Broker 2 - zeebe-cluster-2.zeebe-cluster.svc.cluster.local:26501
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower
  Broker 3 - zeebe-cluster-3.zeebe-cluster.svc.cluster.local:26501
    Partition 1 : Leader
    Partition 2 : Follower
    Partition 3 : Leader
  Broker 4 - zeebe-cluster-4.zeebe-cluster.svc.cluster.local:26501
    Partition 1 : Follower
    Partition 2 : Follower
```

**Comment by kjozsa** [comment] 2020-01-09 15:56
I have put together a Spring Boot/Camel project which can reproduce the RESOURCE_EXHAUSTED issue with the broker backpressure and might be useful for testing this scenario.

Please see the code here: https://github.com/kjozsa/zeebe-hello/ and use the steps at the Quickstart in the README to see the backpressure issue with 0.21.0. Meanwhile I'll re-test with 0.22.0-SNAPSHOT as time allows..

**Comment by eclipdata-gvillacis** [comment] 2020-01-11 03:42
I also have this problem. My scenario is: instantiation of around 500 workflows per minute, I have 3 spring boot workers and each one configured with workerThreads = 3 and maxActiveJobs = 300. I use a single broker. @berndruecker Could you please indicate when we can count on the solution of this issue. My project is about to go to production.

**Comment by Klaus-Nji-sp** [comment] 2020-01-12 15:48
> I also have this problem. My scenario is: instantiation of around 500 workflows per minute, I have 3 spring boot workers and each one configured with workerThreads = 3 and maxActiveJobs = 300. I use a single broker. @berndruecker Could you please indicate when we can count on the solution of this issue. My project is about to go to production.

@eclipdata-gvillacis, what if you use a multiple broker setup?  Do you still run into this issue?  Best practice for a prod deployment scenario will most likely be a multiple broker scenario for load balancer and fault tolerance so you may want to give this setup a try.

**Comment by eclipdata-gvillacis** [comment] 2020-01-12 16:54
@Klaus-Nji-sp 
I have not set up a cluster yet. However, I have seen that other members of the community have sent reports of this problem with a configured cluster.

**Comment by deepthidevaki** [comment] 2020-01-13 14:10
@eclipdata-gvillacis 
In which cases do you observe these errors?
* If the broker receives too many requests that it can handle in a short duration, it is expected to return 'Resource exhausted'. In this case, it should still accept many requests while returning error for some. This is an expected behavior. To verify if this is the case, it would be useful to check the prometheus metrics as mentioned by npenpipe above.
* Did you observe that all requests are rejected with 'Resource exhausted' after the cluster is running for some time? If yes, it could be due to this #3370, which is fixed.

Can you reproduce it on the latest version (0-22.0-alpha2) or snapshot?

**Comment by eclipdata-gvillacis** [comment] 2020-01-15 12:34
@deepthidevaki I observed the error in the first case you described.

I will try release 0.22 and inform.

**Comment by jwulf** [comment] 2020-01-16 16:24
I just updated a system from 0.22.0-alpha1 to -alpha2. I ran on alpha1 for two months and redeployed several times a week without seeing Status 8. Now I see this on application startup:

```
[2020 Jan-16 16:20:44PM] ERROR:
    context: "/server/node_modules/zeebe-node/dist/zb/ZBClient.js:432"
    message: "[deployWorkflow]: Attempt 2 (max: 50)."
    pollInterval: 30000
    namespace: "ZBClient"
[2020 Jan-16 16:20:44PM] ERROR:
    context: "/server/node_modules/zeebe-node/dist/zb/ZBClient.js:440"
    message: "[deployWorkflow]: 8 RESOURCE_EXHAUSTED: Reached maximum capacity of requests handled"
    pollInterval: 30000
    namespace: "ZBClient"
[2020 Jan-16 16:20:46PM] ERROR:
    context: "/server/node_modules/zeebe-node/dist/zb/ZBClient.js:432"
    message: "[deployWorkflow]: Attempt 3 (max: 50)."
    pollInterval: 30000
    namespace: "ZBClient"
[2020 Jan-16 16:20:46PM] ERROR:
    context: "/server/node_modules/zeebe-node/dist/zb/ZBClient.js:440"
    message: "[deployWorkflow]: 8 RESOURCE_EXHAUSTED: Reached maximum capacity of requests handled"
    pollInterval: 30000
    namespace: "ZBClient"
[2020 Jan-16 16:20:50PM] ERROR:
    context: "/server/node_modules/zeebe-node/dist/zb/ZBClient.js:432"
    message: "[deployWorkflow]: Attempt 4 (max: 50)."
    pollInterval: 30000
    namespace: "ZBClient"
[2020 Jan-16 16:20:50PM] ERROR:
    context: "/server/node_modules/zeebe-node/dist/zb/ZBClient.js:440"
    message: "[deployWorkflow]: 8 RESOURCE_EXHAUSTED: Reached maximum capacity of requests handled"
    pollInterval: 30000
    namespace: "ZBClient"
```

**Comment by npepinpe** [comment] 2020-01-16 16:26
I think alpha2 introduced backpressure at the raft level as well, which might be why we're seeing an increase in these errors.

**Comment by deepthidevaki** [comment] 2020-01-17 08:12
@jwulf Do you see any exceptions in broker log? (Related https://github.com/zeebe-io/zeebe/issues/3677#issuecomment-575115884)

**Comment by eclipdata-gvillacis** [comment] 2020-03-25 21:21
If I add another partition to a standalone zeebe do you think this issue will occur less frequently?

**Comment by jwulf** [comment] 2020-04-07 13:56
> If I add another partition to a standalone zeebe do you think this issue will occur less frequently?

Only one way to find out - but my guess is no.

I haven't seen this in a while.

**Comment by menski** [comment] 2020-05-22 07:53
Can anyone confirm that this is still an issue with Zeebe `0.23.1`?

**Comment by gabvillacis** [comment] 2020-05-22 14:20
Hi @menski, Yes, the problem continues to appear. In my case, I have a single Zeebe broker with 3 workers (2 threads each) + 3 workers (1 thread each) and the problem appears when I instantiate the workflows continuously. In one of my use cases, I must create instances of 50 to 100 workflows every 30 minutes, of which about 20 are successfully instantiated but with the others I must apply n retries to be able to instantiate them.

**Comment by menski** [comment] 2020-05-25 07:47
@npepinpe should we keep this issue open or do we have a general back pressure issue?

**Comment by npepinpe** [comment] 2020-05-29 08:36
I'd rather not close this as this highlights a real issue - but at the same time we've learned we need to revisit how we do flow control, so having separate issues there makes sense. But let's not close this one.

**Comment by kjozsa** [comment] 2020-05-29 10:31
Even deploying 5 bpmns sequentally using a dead simple bash script like `for i in *bpmn; do zbctl deploy $i; done` has a good chance of also hitting this error according to our experiences, with 0.23.2.

**Comment by cipianpascu** [comment] 2021-05-21 04:19
Hi Guys,

I get ResourceExhausted also. Continuously, in a normal setting (helm deployment v1.0.0 with 3 nodes and one gateway), with no stress tests.

On the client side:

2021-05-21 03:24:13.668  WARN 1 --- [t-executor-2424] i.c.z.c.j.poller                         : Failed to activated jobs for worker validatorProcessTimeout and job type validatorProcessTimeout
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Expected to activate jobs of type 'validatorProcessTimeout', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.
	at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.37.0.jar!/:1.37.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [grpc-stub-1.37.0.jar!/:1.37.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) [grpc-core-1.37.0.jar!/:1.37.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) [grpc-core-1.37.0.jar!/:1.37.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) [grpc-core-1.37.0.jar!/:1.37.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) [grpc-core-1.37.0.jar!/:1.37.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.37.0.jar!/:1.37.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.37.0.jar!/:1.37.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]


On the cluster side:

  io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot - Failed to delete pending snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/753795-2-909953-909955, checksum=2518679753, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@d0b9db7, metadata=FileBasedSnapshotMetadata{index=753795, term=2, processedPosition=909953, exporterPosition=909955}}
java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/2/pending/753795-2-909953-909955
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists(FileUtil.java:58) ~[zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.abortInternal(FileBasedTransientSnapshot.java:144) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$abort$2(FileBasedTransientSnapshot.java:92) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
[zeebe-2.log](https://github.com/camunda-cloud/zeebe/files/6519971/zeebe-2.log)
[zeebe-0.log](https://github.com/camunda-cloud/zeebe/files/6519972/zeebe-0.log)
[zeebe-1.log](https://github.com/camunda-cloud/zeebe/files/6519973/zeebe-1.log)

I attached the logs for all three nodes also.

[zeebe-1.log](https://github.com/camunda-cloud/zeebe/files/6520007/zeebe-1.log)
[zeebe-2.log](https://github.com/camunda-cloud/zeebe/files/6520008/zeebe-2.log)
[zeebe-0.log](https://github.com/camunda-cloud/zeebe/files/6520009/zeebe-0.log)
[gateway.log](https://github.com/camunda-cloud/zeebe/files/6520004/gateway.log)

Kind regards,
Ciprian

**Comment by jwulf** [comment] 2021-05-27 09:24
> I get ResourceExhausted also. Continuously, in a normal setting (helm deployment v1.0.0 with 3 nodes and one gateway), with no stress tests.
> 

Hi @cipianpascu, what resources are you allocating to the cluster?

**Comment by cipianpascu** [comment] 2021-05-27 10:21
![image](https://user-images.githubusercontent.com/1932486/119809753-1c3a2a80-beee-11eb-88ba-4273a27f6bb4.png)

Hi Josh,

I have one kubernetes cluster with plenty of resources. Memory for each node 16Gb, with 4 cores and with 10Gb network connection for the storage. I attached a screenshot. 

Thank you,
Ciprian

**Comment by npepinpe** [comment] 2021-06-15 08:40
I'm fairly certain this issue is due to using VegasLimit for backpressure. It's known to behave poorly if you don't feed it a ramp up phase, where you grow the expected threshold. You can use different back pressure algorithms - for predictable performance, I would suggest you use the fixed limit and benchmark your expected loads find the right limit for your use case. I hope we can provide a better implementation which doesn't need a ramp up phase soon, but for now I would recommend the fixed limit. See the [doc](https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/operations/backpressure) for more.

**Closed by npepinpe** 2021-06-15 08:40 UTC
Labels: Impact: Performance, Impact: Usability, Severity: Mid, Status: Needs Information, Type: Bug
