### ISSUE TITLE
LongPollingActivateJobsTest#shouldUseLargeRequestTimeout is flaky

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#8418] opened 2021-12-16 16:31 UTC
**Summary**

- How often does the test fail?
  - only once so far
- Does it block your work?
  - no, just annoying
- Do we suspect that it is a real failure?
  -  can't say yet

**Failures**

[Failing build: please delete once done, as it's marked to be kept forever](https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/staging/1520/)

<details><summary>Example assertion failure</summary>
<pre>
Wanted but not invoked:
serverStreamObserver.onCompleted();
-> at io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldUseLargeRequestTimeout(LongPollingActivateJobsTest.java:327)

However, there were exactly 8 interactions with this mock:
serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:109)

serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:109)

serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:109)

serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:109)

serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:109)

serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:109)

serverStreamObserver.isCancelled();
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.isCanceled(LongPollingActivateJobsRequest.java:109)

serverStreamObserver.onNext(
    jobs {
  key: 9007199254740992
  type: "test"
  processInstanceKey: 123
  bpmnProcessId: "stubProcess"
  processDefinitionVersion: 23
  processDefinitionKey: 4532
  elementId: "stubActivity"
  elementInstanceKey: 459
  customHeaders: "{\"foo\":12,\"bar\":\"val\"}"
  retries: 12
  deadline: 123123123
  variables: "{\"foo\":13,\"bar\":\"world\"}"
}

);
-> at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsRequest.onResponse(LongPollingActivateJobsRequest.java:84)

	at io.camunda.zeebe.gateway.api.job.LongPollingActivateJobsTest.shouldUseLargeRequestTimeout(LongPollingActivateJobsTest.java:327)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
</pre>
</details>

**Logs**

<details><summary>Logs</summary>
<pre>
16:02:19.671 [main] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
16:02:19.671 [main] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
16:02:19.675 [-zb-fs-workers-1] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
16:02:19.677 [-zb-actors-6] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
</pre>
</details>

**Comment by Zelldon** [comment] 2022-01-04 14:28
I can't reproduce it. Taking a look at the code I see also no reason why this can happen. I can imagine that this was fixed due to some of the earlier PR's https://github.com/camunda-cloud/zeebe/pull/8391 or https://github.com/camunda-cloud/zeebe/pull/8392 made by @romansmirnov 

I will close this for now correct me if I'm wrong and feel free to reopen it.

**Closed by Zelldon** 2022-01-04 14:28 UTC
Labels: Type: Unstable Test
