### ISSUE TITLE
Zeebe Partition falsely marked as unhealthy

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#8462] opened 2021-12-21 14:36 UTC
**Describe the bug**

A recent benchmark ran into a problem with ES, which led to the ES exporter not being able to export, which led to not being able to compact the log, which led to Out Of Disk (OOD) due to disk watermark, which is detected and leads to the partitions being marked UNHEALTHY.

After fixing the ES, problem (i.e. changing the deployed version in zeebe-values.yaml), the ES exporter could export again, which meant we could compact the log and resolve the OOD. However, the partitions were still marked UNHEALTHY even though processing had started again.

[Link to Grafana](http://34.77.165.228/d/I4lo7_EZk/zeebe?orgId=1&var-DS_PROMETHEUS=Prometheus&var-namespace=release-1-3-0&var-pod=All&var-partition=All&from=1640086778162&to=1640096041955).

<img width="1624" alt="Screen Shot 2021-12-21 at 15 27 35" src="https://user-images.githubusercontent.com/3511026/146946122-eac3330e-8d56-46f2-8474-c63be7a8b2a2.png">

**To Reproduce**

- spin up a Zeebe cluster (e.g. the benchmark project)
- break ES
- wait for OOD
- unbreak ES

**Expected behavior**

Partition should've been marked as HEALTHY again.

**Log**

<details><summary>Filtered Logs</summary>
 <p>

[More logs](https://cloudlogging.app.goo.gl/5SgYwyJPDhhqD7mR6).
[Subset of Logs stored in Drive](https://drive.google.com/file/d/1QQtbAnvHgWeN8pi3tjajxfpSt7ft5O-e/view?usp=sharing)

```
"Detected 'UNHEALTHY' components. The current health status of components: [Broker-2-Exporter-2{status=HEALTHY}, ZeebePartition-2{status=UNHEALTHY, issue='Not enough disk space available'}, raft-partition-partition-2{status=HEALTHY}, Broker-2-SnapshotDirector-2{status=HEALTHY}, Broker-2-StreamProcessor-2{status=HEALTHY}, Broker-2-LogStream-2{status=HEALTHY}]"
"Detected 'UNHEALTHY' components. The current health status of components: [Partition-2{status=UNHEALTHY, issue=ZeebePartition-2{status=UNHEALTHY, issue='Not enough disk space available'}}, Partition-1{status=UNHEALTHY, issue=ZeebePartition-1{status=UNHEALTHY, issue='Not enough disk space available'}}, Partition-3{status=UNHEALTHY, issue=ZeebePartition-3{status=UNHEALTHY, issue='Not enough disk space available'}}]"
"Detected 'UNHEALTHY' components. The current health status of components: [Broker-2-Exporter-3{status=HEALTHY}, ZeebePartition-3{status=UNHEALTHY, issue='Not enough disk space available'}, raft-partition-partition-3{status=HEALTHY}, Broker-2-LogStream-3{status=HEALTHY}, Broker-2-SnapshotDirector-3{status=HEALTHY}, Broker-2-StreamProcessor-3{status=HEALTHY}]"
"Detected 'UNHEALTHY' components. The current health status of components: [ZeebePartition-1{status=UNHEALTHY, issue='Not enough disk space available'}, raft-partition-partition-1{status=HEALTHY}, Broker-2-Exporter-1{status=HEALTHY}, Broker-2-StreamProcessor-1{status=HEALTHY}, Broker-2-LogStream-1{status=HEALTHY}, Broker-2-SnapshotDirector-1{status=HEALTHY}]"
"Partition-1 failed, marking it as unhealthy: Broker-2{status=UNHEALTHY, issue=Partition-2{status=UNHEALTHY, issue=ZeebePartition-2{status=UNHEALTHY, issue='Not enough disk space available'}}}"
"Detected 'UNHEALTHY' components. The current health status of components: [Partition-2{status=UNHEALTHY, issue=ZeebePartition-2{status=UNHEALTHY, issue='Not enough disk space available'}}, Partition-1{status=UNHEALTHY, issue=ZeebePartition-1{status=UNHEALTHY, issue='Not enough disk space available'}}, Partition-3{status=UNHEALTHY, issue=ZeebePartition-3{status=UNHEALTHY, issue='Not enough disk space available'}}]"
"Detected 'UNHEALTHY' components. The current health status of components: [Broker-2-Exporter-2{status=HEALTHY}, ZeebePartition-2{status=UNHEALTHY, issue='Not enough disk space available'}, raft-partition-partition-2{status=HEALTHY}, Broker-2-SnapshotDirector-2{status=HEALTHY}, Broker-2-StreamProcessor-2{status=HEALTHY}, Broker-2-LogStream-2{status=HEALTHY}]"
"Detected 'UNHEALTHY' components. The current health status of components: [Partition-2{status=UNHEALTHY, issue=ZeebePartition-2{status=UNHEALTHY, issue='Not enough disk space available'}}, Partition-1{status=UNHEALTHY, issue=ZeebePartition-1{status=UNHEALTHY, issue='Not enough disk space available'}}, Partition-3{status=UNHEALTHY, issue=ZeebePartition-3{status=UNHEALTHY, issue='Not enough disk space available'}}]"
```

</p>
</details>

**Environment:**
 - OS: `zeebe-io`
 - Zeebe Version: `release-1.3.0`
 - Configuration: benchmark

**Comment by Zelldon** [comment] 2021-12-21 14:53
Duplicate of: https://github.com/camunda-cloud/zeebe/issues/6232 or https://github.com/camunda-cloud/zeebe/issues/6393 and I think there are other related

**Comment by npepinpe** [comment] 2021-12-28 12:52
Closing as duplicate and we'll reprioritize the other one

**Closed by npepinpe** 2021-12-28 12:52 UTC
Labels: Type: Bug
