### ISSUE TITLE
ZeebeWorker  request ActivatedJob in zeebe but get no response 

### ISSUE THREAD

**Issue by jerry123888** [camunda-cloud/zeebe#8759] opened 2022-02-10 06:30 UTC
**Describe the bug:**
Ramdomly and not often, a worker requesting ActivateJobs on Zeebe get an empty answer, but the job is activated in Zeebe so it will never be done.

**Evn:**
zeebe 1.2.4
java-client sdk
![image](https://user-images.githubusercontent.com/92800459/153341509-df3528ba-0182-4cbc-80ad-7421ef601951.png)

**Settings:**
PARTITIONSCOUNT=9
BROKER_CLUSTER_CLUSTERSIZE=3
request_time_out=10s

**Job worker code:**
![image](https://user-images.githubusercontent.com/92800459/153341737-57a1c4fe-0c17-499c-a622-092ebff3a06a.png)

**Test method:**

1)create instance constantly by different QPS:
create instance code like this:
![image](https://user-images.githubusercontent.com/92800459/153348269-60807176-d4af-4605-b33b-0b1d2b3f8eea.png)
![image](https://user-images.githubusercontent.com/92800459/153348353-cd6a7483-600a-4c3c-a334-60d52509aa84.png)

2)observe the result:
for example, i create totally 100 instances, each instance has 30 jobs, so i expect there are 100*30=3000 jobs will be finished in the end.
but unfortunately , someone jobs will standing always running state ramdomly in fact .

**Test result:**
1) just like the bug describtion, a worker requesting ActivateJobs on Zeebe get an empty answer, but the job is activated in Zeebe so it will never be done.
2) by improving  "request_time_out"  into 30s, 60s, but  it does not make sence.
3) by improving  "PARTITIONSCOUNT" into 18、27、54, also no use.

Add a similar issues ：https://github.com/camunda-cloud/zeebe/issues/5925

**Comment by jerry123888** [comment] 2022-02-10 06:39
#5925

**Comment by npepinpe** [comment] 2022-02-15 11:05
I think this is a duplicate of https://github.com/camunda-cloud/zeebe/issues/8622, or at least the root cause that was found would also be the root cause here. Feel free to reopen if you think otherwise.

**Closed by npepinpe** 2022-02-15 11:05 UTC

**Comment by npepinpe** [comment] 2022-02-20 21:36
Yes, we plan to work on this soon, though I can't really say how long it will take. We've identified a couple issues, which together aggravate the situation (not handling cancellation/aborted calls properly, not being able to extend job timeouts, not being able to yield jobs when we know a client went away), but all of these would mitigating the issue. It might still be worth doing, but I would also like that we review our approach in general when it comes to handling jobs/external service tasks.
