### ISSUE TITLE
io.atomix.raft.storage.StorageException: Failed to acquire storage lock

### ISSUE THREAD

**Issue by denissabramovs** [camunda-cloud/zeebe#7183] opened 2021-06-03 13:23 UTC
**Describe the bug**
Can't start pods of brokers. Health checks are failing. There is error in the logs.

`Caused by: io.atomix.raft.storage.StorageException: Failed to acquire storage lock; ensure each Raft server is configured with a distinct storage directory`

**To Reproduce**
Use latest alpha image in kubernetes/docker

**Expected behavior**
All brokers are up and running.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673279635Z Caused by: java.util.concurrent.CompletionException: io.atomix.raft.storage.StorageException: Failed to acquire storage lock; ensure each Raft server is configured with a distinct storage directory
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673301646Z      at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673305654Z      at java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673309241Z      at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673314420Z      at java.util.concurrent.CompletableFuture.thenApply(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673318588Z      at io.atomix.raft.partition.RaftPartition.open(RaftPartition.java:120) ~[zeebe-atomix-cluster-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673322245Z      at io.atomix.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:201) ~[zeebe-atomix-cluster-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673326052Z      at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673329639Z      at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673333166Z      at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673336662Z      at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673340268Z      at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673343806Z      at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673347352Z      at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673350919Z      at io.atomix.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:203) ~[zeebe-atomix-cluster-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673354726Z      at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:80) ~[zeebe-atomix-cluster-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673358443Z      at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673362000Z      at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673365656Z      at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673369233Z      at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673372740Z      at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673376316Z      at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673380054Z      at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673383590Z      at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:81) ~[zeebe-atomix-cluster-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673387298Z      at io.atomix.core.Atomix.lambda$startServices$0(Atomix.java:178) ~[zeebe-atomix-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673395132Z      at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673399761Z      at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673403508Z      at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) ~[zeebe-atomix-utils-1.1.0-alpha1.jar:1.1.0-alpha1]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673407235Z      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673410772Z      at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673414199Z      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673417775Z      at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673421292Z      at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
zeebe-cluster-zeebe-2 zeebe-cluster 2021-06-03T12:56:20.673424738Z      at java.lang.Thread.run(Unknown Source) ~[?:?]
```

</p>
</details>

**Environment:**
 - OS: Linux/Kubernetes
 - Zeebe Version: 1.1.0-alpha1
 - Configuration: default

**Comment by denissabramovs** [comment] 2021-06-03 13:28
After **completely** deleting volume claims and recreating pods, it worked. But that means, that there is backward compatibility issue from v1.

**Comment by denissabramovs** [comment] 2021-06-03 13:37
Found configuration in logs:

```
2021-06-03 13:35:39.816 [] [main] INFO 
      io.camunda.zeebe.broker.system - Starting broker 1 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 26501,
      "advertisedHost" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local",
      "advertisedPort" : 26501,
      "address" : "0.0.0.0:26501",
      "advertisedAddress" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local:26501"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 26502,
      "advertisedHost" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local",
      "advertisedPort" : 26502,
      "address" : "0.0.0.0:26502",
      "advertisedAddress" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local:26502"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 9600,
      "advertisedHost" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local",
      "advertisedPort" : 9600,
      "address" : "0.0.0.0:9600",
      "advertisedAddress" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "zeebe-cluster-zeebe-0.zeebe-cluster-zeebe.api.svc.cluster.local:26502", "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local:26502", "zeebe-cluster-zeebe-2.zeebe-cluster-zeebe.api.svc.cluster.local:26502" ],
    "partitionIds" : [ 1, 2, 3 ],
    "nodeId" : 1,
    "partitionsCount" : 3,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster-zeebe",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directory" : "/usr/local/zeebe/data",
    "logSegmentSize" : "128MB",
    "snapshotPeriod" : "PT5M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.99,
    "diskUsageCommandWatermark" : 0.97,
    "diskUsageMonitoringInterval" : "PT1S",
    "logSegmentSizeInBytes" : 134217728,
    "freeDiskSpaceCommandWatermark" : 315053138,
    "freeDiskSpaceReplicationWatermark" : 105017713
  },
  "exporters" : {
    "elasticsearch" : {
      "jarPath" : null,
      "className" : "io.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "url" : "http://elasticsearch-master:9200"
      },
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT0.1S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      }
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "initialized" : true,
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "32KB",
    "disableExplicitRaftFlush" : false,
    "rocksdb" : {
      "columnFamilyOptions" : { },
      "enableStatistics" : false,
      "memoryLimit" : "512MB",
      "maxOpenFiles" : -1,
      "maxWriteBufferNumber" : 6,
      "minWriteBufferNumberToMerge" : 3,
      "ioRateBytesPerSecond" : 0,
      "disableWal" : false
    },
    "maxAppendBatchSizeInBytes" : 32768
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
```

**Comment by denissabramovs** [comment] 2021-06-03 13:38
Found configuration in logs:

```
2021-06-03 13:35:39.816 [] [main] INFO 
      io.camunda.zeebe.broker.system - Starting broker 1 with configuration {
  "network" : {
    "host" : "0.0.0.0",
    "portOffset" : 0,
    "maxMessageSize" : "4MB",
    "advertisedHost" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local",
    "commandApi" : {
      "host" : "0.0.0.0",
      "port" : 26501,
      "advertisedHost" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local",
      "advertisedPort" : 26501,
      "address" : "0.0.0.0:26501",
      "advertisedAddress" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local:26501"
    },
    "internalApi" : {
      "host" : "0.0.0.0",
      "port" : 26502,
      "advertisedHost" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local",
      "advertisedPort" : 26502,
      "address" : "0.0.0.0:26502",
      "advertisedAddress" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local:26502"
    },
    "monitoringApi" : {
      "host" : "0.0.0.0",
      "port" : 9600,
      "advertisedHost" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local",
      "advertisedPort" : 9600,
      "address" : "0.0.0.0:9600",
      "advertisedAddress" : "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local:9600"
    },
    "maxMessageSizeInBytes" : 4194304
  },
  "cluster" : {
    "initialContactPoints" : [ "zeebe-cluster-zeebe-0.zeebe-cluster-zeebe.api.svc.cluster.local:26502", "zeebe-cluster-zeebe-1.zeebe-cluster-zeebe.api.svc.cluster.local:26502", "zeebe-cluster-zeebe-2.zeebe-cluster-zeebe.api.svc.cluster.local:26502" ],
    "partitionIds" : [ 1, 2, 3 ],
    "nodeId" : 1,
    "partitionsCount" : 3,
    "replicationFactor" : 3,
    "clusterSize" : 3,
    "clusterName" : "zeebe-cluster-zeebe",
    "membership" : {
      "broadcastUpdates" : false,
      "broadcastDisputes" : true,
      "notifySuspect" : false,
      "gossipInterval" : "PT0.25S",
      "gossipFanout" : 2,
      "probeInterval" : "PT1S",
      "probeTimeout" : "PT0.1S",
      "suspectProbes" : 3,
      "failureTimeout" : "PT10S",
      "syncInterval" : "PT10S"
    }
  },
  "threads" : {
    "cpuThreadCount" : 2,
    "ioThreadCount" : 2
  },
  "data" : {
    "directory" : "/usr/local/zeebe/data",
    "logSegmentSize" : "128MB",
    "snapshotPeriod" : "PT5M",
    "logIndexDensity" : 100,
    "diskUsageMonitoringEnabled" : true,
    "diskUsageReplicationWatermark" : 0.99,
    "diskUsageCommandWatermark" : 0.97,
    "diskUsageMonitoringInterval" : "PT1S",
    "logSegmentSizeInBytes" : 134217728,
    "freeDiskSpaceCommandWatermark" : 315053138,
    "freeDiskSpaceReplicationWatermark" : 105017713
  },
  "exporters" : {
    "elasticsearch" : {
      "jarPath" : null,
      "className" : "io.zeebe.exporter.ElasticsearchExporter",
      "args" : {
        "url" : "http://elasticsearch-master:9200"
      },
      "external" : false
    }
  },
  "gateway" : {
    "network" : {
      "host" : "0.0.0.0",
      "port" : 26500,
      "minKeepAliveInterval" : "PT30S"
    },
    "cluster" : {
      "contactPoint" : "0.0.0.0:26502",
      "requestTimeout" : "PT15S",
      "clusterName" : "zeebe-cluster",
      "memberId" : "gateway",
      "host" : "0.0.0.0",
      "port" : 26502,
      "membership" : {
        "broadcastUpdates" : false,
        "broadcastDisputes" : true,
        "notifySuspect" : false,
        "gossipInterval" : "PT0.25S",
        "gossipFanout" : 2,
        "probeInterval" : "PT1S",
        "probeTimeout" : "PT0.1S",
        "suspectProbes" : 3,
        "failureTimeout" : "PT10S",
        "syncInterval" : "PT10S"
      }
    },
    "threads" : {
      "managementThreads" : 1
    },
    "monitoring" : {
      "enabled" : false,
      "host" : "0.0.0.0",
      "port" : 9600
    },
    "security" : {
      "enabled" : false,
      "certificateChainPath" : null,
      "privateKeyPath" : null
    },
    "longPolling" : {
      "enabled" : true
    },
    "initialized" : true,
    "enable" : false
  },
  "backpressure" : {
    "enabled" : true,
    "algorithm" : "VEGAS",
    "aimd" : {
      "requestTimeout" : "PT1S",
      "initialLimit" : 100,
      "minLimit" : 1,
      "maxLimit" : 1000,
      "backoffRatio" : 0.9
    },
    "fixed" : {
      "limit" : 20
    },
    "vegas" : {
      "alpha" : 3,
      "beta" : 6,
      "initialLimit" : 20
    },
    "gradient" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0
    },
    "gradient2" : {
      "minLimit" : 10,
      "initialLimit" : 20,
      "rttTolerance" : 2.0,
      "longWindow" : 600
    }
  },
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "32KB",
    "disableExplicitRaftFlush" : false,
    "rocksdb" : {
      "columnFamilyOptions" : { },
      "enableStatistics" : false,
      "memoryLimit" : "512MB",
      "maxOpenFiles" : -1,
      "maxWriteBufferNumber" : 6,
      "minWriteBufferNumberToMerge" : 3,
      "ioRateBytesPerSecond" : 0,
      "disableWal" : false
    },
    "maxAppendBatchSizeInBytes" : 32768
  },
  "stepTimeout" : "PT5M",
  "executionMetricsExporterEnabled" : false
}
```

**Comment by denissabramovs** [comment] 2021-06-03 14:01
After recreating everything, it is working now. So i guess this can be considered as backward compatibility issue related to existing data on volumes.

**Comment by deepthidevaki** [comment] 2021-06-07 06:31
I couldn't reproduce it. I started a broker with 1.1.0-alpha1 with data generated by 1.0.0. The broker was able to successfully start with out losing the previous data. So I would say there is no compatibility issue between these two versions.

@denissabramovs Are you able to reproduce this?

`Failed to acquire storage lock ` error usually happens due to misconfiguration of `data.directory`.  If the brokers share the data folder, they attempt to write to the same files which causes this error.

**Comment by denissabramovs** [comment] 2021-06-07 08:22
Nope, could be a single case, could be that kubernetes assigned a single volume to multiple nodes, but i doubt it.
In any case, after upgrading to new version and restarting all nodes, it is working now.

**Comment by deepthidevaki** [comment] 2021-06-07 11:58
Thanks. Then I am closing this issue.

**Closed by deepthidevaki** 2021-06-07 11:58 UTC
Labels: Type: Question
