### ISSUE TITLE
I can't activate jobs with a high max job count

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#5525] opened 2020-10-07 11:52 UTC
**Describe the bug**

Reported by an user I have investigate an issue where it seems they are not able to activate more jobs. They changed the default configuration of the `maxMessageSize` to `128KB` and experienced errors in the broker which indicate that job batch record is to large.

**To Reproduce**
 * Run a cluster with `maxMessageSize` set to `128KB`
 * Run our starters to create a backlog of jobs
 * Start an worker locally with `maxActivationCount` 1000+
 * FetchVariables needs to be set to "" otherwise we will fetch all variables in our benchmarks and it seem to work that the splitting of job activation succeeds

If we set the FetchVariables to empty, then the broker seems to try to put more jobs into the job activation and fails on doing that.

```csharp
                client.NewWorker()
                      .JobType(JobType)
                      .Handler(HandleJob)
                      .MaxJobsActive(5000)
                      .Name(WorkerName)
                      .AutoCompletion()
                      .PollInterval(TimeSpan.FromSeconds(1))
                      .Timeout(TimeSpan.FromSeconds(10))
                      .FetchVariables("")
                      .Open();
```

**Expected behavior**
I can activate jobs without issues. If the max message size is reached it will still returned me jobs up to the specific limit.

**Log/Stacktrace**
https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2020-10-07T11:40:15.009000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-small-msg-size%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-small-msg-size%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22&scrollTimestamp=2020-10-07T11:39:38.166836000Z&pinnedLogId=hrguh6fg7uydd&pinnedLogTimestamp=2020-10-07T11:39:38.166836Z

<details><summary>Full Stacktrace</summary>
 <p>

```
Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE, requestStreamId=1, requestId=533714, protocolVersion=2, valueType=JOB_BATCH, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=0.25.0}, value={"type":"benchmark-task","worker":"zell-T490","timeout":10000,"maxJobsToActivate":5000,"jobKeys":[2251799820188250,2251799820188259,2251799820188260,2251799820188282,2251799820188295,2251799820188296,2251799820188393,2251799820188400,2251799820188401,2251799820188429,2251799820188526,2251799820188557,2251799820188600,2251799820188601,2251799820188811,2251799820188851,2251799820188853,2251799820188854,2251799820188855,2251799820188857,2251799820188858,2251799820188864,2251799820188866,2251799820188875,2251799820188895,2251799820188896,2251799820188897,2251799820188898,2251799820188916,2251799820188942,2251799820189019,2251799820189048,2251799820189062,2251799820189067,2251799820189068,2251799820189082,2251799820189083,2251799820189090,2251799820189094,2251799820189097,2251799820189098,2251799820189099,2251799820189163,2251799820189166,2251799820189189,2251799820189206,2251799820189229,2251799820189230,2251799820189232,2251799820189259,2251799820189267,2251799820189309,2251799820189343,2251799820189393,22517998...}' without errors, but exception occurred with message 'Expected to claim segment of size 152616, but can't claim more than 131072 bytes.' ." 
```

</p>
</details>

**Environment:**
 - OS: k8s
 - Zeebe Version: 0.24.2, 0.25.0-SNAPSHOT
 - Configuration: default + maxMessageSize = 128KB

**Comment by npepinpe** [comment] 2020-10-08 07:58
Let's make sure we properly handle not returning more jobs than we can fit in there.

**Comment by Zelldon** [comment] 2020-10-26 08:48
found an related old issue  https://github.com/zeebe-io/zeebe/issues/1578

**Comment by korthout** [comment] 2020-11-06 15:51
Linked [error](https://console.cloud.google.com/errors/CJ_PxYKiyLyp8QE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1) on camunda cloud.

**Comment by npepinpe** [comment] 2020-11-09 15:21
I'm downgrading this, as while I still think this is necessary for GA, it's not necessary immediately.

**Comment by Zelldon** [comment] 2020-12-10 07:15
Might be fixed or at least the chance that this happens is reduced by https://github.com/zeebe-io/zeebe/pull/5991

**Comment by falko** [comment] 2021-01-25 18:16
My current customer emphasized the importance of this issue again.

**Comment by Zelldon** [comment] 2021-01-26 06:51
@falko which version are they using?

**Comment by falko** [comment] 2021-02-22 15:30
Last time my customer reproduced it 0.25.3. Now they are using 0.26 but trying to avoid the issue with workarounds

**Comment by falko** [comment] 2021-02-22 15:31
Are you planning to include this in 1.0.0?

**Comment by npepinpe** [comment] 2021-02-22 15:33
It doesn't look like it at the moment - feel free to bring it up in the stakeholder meetings if you think it should have higher priority.

**Comment by npepinpe** [comment] 2021-09-08 15:45
I cannot reproduce this anymore. Here's a small reproducer, let me know if I'm doing something wrong:

<details><summary>Reproducer</summary>

```java
package io.camunda.zeebe.it.client;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

import io.camunda.zeebe.broker.StandaloneBroker;
import io.camunda.zeebe.broker.system.configuration.BrokerCfg;
import io.camunda.zeebe.client.ZeebeClient;
import io.camunda.zeebe.client.api.ZeebeFuture;
import io.camunda.zeebe.client.api.command.CreateProcessInstanceCommandStep1.CreateProcessInstanceCommandStep2;
import io.camunda.zeebe.client.api.command.FinalCommandStep;
import io.camunda.zeebe.client.api.response.ActivateJobsResponse;
import io.camunda.zeebe.it.smoke.CollectorRegistryInitializer;
import io.camunda.zeebe.it.smoke.RandomPortInitializer;
import io.camunda.zeebe.model.bpmn.Bpmn;
import io.camunda.zeebe.protocol.record.intent.JobIntent;
import io.camunda.zeebe.test.util.asserts.TopologyAssert;
import io.camunda.zeebe.test.util.record.RecordingExporter;
import java.time.Duration;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@SpringBootTest(
    webEnvironment = WebEnvironment.RANDOM_PORT,
    classes = StandaloneBroker.class,
    properties = {
      "zeebe.broker.exporters.recording.className=io.camunda.zeebe.test.util.record.RecordingExporter",
      "zeebe.broker.network.maxMessageSize=128KB"
    })
@ContextConfiguration(
    initializers = {RandomPortInitializer.class, CollectorRegistryInitializer.class})
@ActiveProfiles("test")
final class JobActivationIT {

  @SuppressWarnings("unused")
  @Autowired
  private BrokerCfg config;

  @BeforeEach
  void beforeEach() {
    await("until broker is ready").untilAsserted(this::assertBrokerIsReady);

    try (final var client = createClient()) {
      await("until topology is complete").untilAsserted(() -> assertTopologyIsComplete(client));
    }
  }

  @Test
  void shouldActivateLargeAmountsOfJobs() {
    // given
    final var process =
        Bpmn.createExecutableProcess("process")
            .startEvent()
            .serviceTask("task", b -> b.zeebeJobType("type"))
            .endEvent()
            .done();
    final var payload = Map.of("foo", "x".repeat(16 * 1024));
    final var jobCount = 2000;

    final ActivateJobsResponse response;
    try (final var client = createClient()) {

      client.newDeployCommand().addProcessModel(process, "process.bpmn").send().join();
      IntStream.range(0, jobCount)
          .mapToObj(i -> client.newCreateInstanceCommand())
          .map(cmd -> cmd.bpmnProcessId("process"))
          .map(CreateProcessInstanceCommandStep2::latestVersion)
          .map(cmd -> cmd.variables(payload))
          .map(FinalCommandStep::send)
          .forEach(ZeebeFuture::join);

      await("until all jobs are created")
          .atMost(Duration.ofSeconds(30))
          .untilAsserted(
              () ->
                  assertThat(
                          RecordingExporter.jobRecords(JobIntent.CREATED)
                              .collect(Collectors.toList()))
                      .hasSize(jobCount));

      // when
      response =
          client
              .newActivateJobsCommand()
              .jobType("type")
              .maxJobsToActivate(jobCount)
              .fetchVariables("")
              .send()
              .join();
    }

    // then
    assertThat(response.getJobs()).hasSizeGreaterThan(0);
  }

  private void assertBrokerIsReady() {
    given()
        .port(config.getNetwork().getMonitoringApi().getPort())
        .when()
        .get("/ready")
        .then()
        .statusCode(204);
  }

  private void assertTopologyIsComplete(final ZeebeClient client) {
    TopologyAssert.assertThat(client.newTopologyRequest().send().join()).isComplete(1, 1);
  }

  private ZeebeClient createClient() {
    return ZeebeClient.newClientBuilder()
        .usePlaintext()
        .gatewayAddress("localhost:" + config.getGateway().getNetwork().getPort())
        .build();
  }
}
```

</details>

The test case works as follows:

- Start a new broker with embedded gateway, with max message size 128KB
- Deploy a process with a single service task
- Create `jobCount = 2000` process instances to create effectively 2000 activatable jobs
- Wait until all jobs have been created
- Try to activate `jobCount = 2000` jobs in a single command

The expectation is we could activate some of them, which works at the moment. From the issue description, it sounds like nothing could be activated?

Let me know, otherwise we could close this, as this was pre 1.0.

NOTE: do not do these kind of tests at home :sweat_smile: Once we have an IPC exporter I'd rather use a container based tests, but this was sufficient for now.

**Comment by npepinpe** [comment] 2021-09-09 17:24
I'm closing this tentatively, maybe when Zelldon is back he can try with his old reproducer and see if it still occurs.

**Comment by Zelldon** [comment] 2021-12-02 07:08
Was reported by an user with 1.2.4 via slack https://camunda-cloud.slack.com/archives/C6WGNHV2A/p1638415339196500

```
Hi guys, I am using zeebe 1.2.4 and getting this error due to which see the brokers in unhealthy state. Any suggestion onn how to resolve it?io.camunda.zeebe.processor - Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=ACTIVATE, requestStreamId=2, requestId=574478, protocolVersion=3, valueType=JOB_BATCH, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=1.2.4}, value={"type":"ram","worker":"default","timeout":10,"maxJobsToActivate":520,"jobKeys":[4503599638791419,4503599638791474,4503599638791553,4503599638791698,4503599638792095,4503599638792142,4503599638792614,4503599638793795,4503599638793808,4503599638793815,4503599638793831,4503599638794152,4503599638794246,4503599638794386,4503599638794393,4503599638794427,4503599638795132,4503599638795677,4503599638796265,4503599638797006,4503599638797349,4503599638797370,4503599638797381,4503599638797524,4503599638797561,4503599638797564,4503599638797604,4503599638797626,4503599638797866,4503599638798108,4503599638798433,4503599638799326,4503599638799746,4503599638799985,4503599638799989,4503599638800553,4503599638801856,4503599638802110,4503599638802277,4503599638802415,4503599638802552,4503599638802909,4503599638803041,4503599638803426,4503599638803703,4503599638804009,4503599638804578,4503599638804648,4503599638804779,4503599638804880,4503599638804912,4503599638804994,4503599638805221,4503599638805394,4503599638805435,45035996...}' without errors, but exception occurred with message 'Expected to claim segment of size 20974720, but can't claim more than 20971520 bytes.'.
```

**Comment by npepinpe** [comment] 2021-12-06 09:13
We did calculate a bit of overhead, but I guess the calculation is still too strict.

**Comment by npepinpe** [comment] 2021-12-06 16:49
I can reproduce it with the following test:

<details><summary>ActivateJobsTest#shouldActivateJobUpToMaxMessageSize</summary>

```java
  @Test
  public void shouldActivateJobUpToMaxMessageSize() {
    // given
    final var maxMessageSize = ByteValue.ofMegabytes(4);
    final var headerSize = ByteValue.ofKilobytes(2);
    final var maxRecordSize = maxMessageSize - headerSize;

    ENGINE.deployment().withXmlResource(PROCESS_ID, MODEL_SUPPLIER.apply(taskType)).deploy();
    final var processInstanceKey = ENGINE.processInstance().ofBpmnProcessId(PROCESS_ID).create();
    final var processInstanceKey2 = ENGINE.processInstance().ofBpmnProcessId(PROCESS_ID).create();

    // since the variable update will write the variable twice, we need to split this off
    final var variablesSize = (int) maxRecordSize / 2;
    await("until the job is created")
        .untilAsserted(
            () ->
                assertThat(
                        jobRecords(JobIntent.CREATED)
                            .withType(taskType)
                            .filter(r -> processInstanceKey == r.getValue().getProcessInstanceKey())
                            .limit(1))
                    .hasSize(1));
    ENGINE
        .variables()
        .withDocument(Map.of("foo", "x".repeat(variablesSize)))
        .ofScope(processInstanceKey)
        .update();
    ENGINE
        .variables()
        .withDocument(Map.of("bar", "x".repeat(variablesSize)))
        .ofScope(processInstanceKey2)
        .update();
    ENGINE
        .variables()
        .withDocument(Map.of("foo", "x".repeat(1200)))
        .ofScope(processInstanceKey2)
        .update();
    ENGINE
        .variables()
        .withDocument(Map.of("baz", "x".repeat(6)))
        .ofScope(processInstanceKey2)
        .update();

    // when
    final var jobs =
        ENGINE.jobs().withType(taskType).withMaxJobsToActivate(2).activate().getValue();

    // then

  }
```

</details>

There's no assertions but you'll see the engine loop forever throwing an exception.

That brings me to two issues: 1) this is not a recoverable error AFAIK, so we should probably bail early. 2) I could fix it in particular here, but I think this has a chance of happening in different processors, so it might be better to build a mechanism where we can react to such errors, possibly by delegating the error handling to the processor (with a generic error handling in the processing state machine?).

**Comment by npepinpe** [comment] 2021-12-08 20:58
The proper calculation would be as follows:

`maxJobBatchRecordValueSize = maxMessageSize - sizeOfRecordWithoutValue`

Then when we add jobs, on every iteration, we check if the value's length is less than that. Right now, we simply don't do that, but instead use the `maxMessageSize` directly, so sometimes things end up spilling over.

**Closed** 2022-02-23 13:18 UTC
Labels: Type: Bug, Scope: broker, Impact: Availability, Severity: High
