### ISSUE TITLE
java.io.IOException: Input/output error in MetaStore.storeVote while stepping down

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#5778] opened 2020-11-06 16:11 UTC
**Describe the bug**
A `java.io.IOException: Input/output error` occurred in `MetaStore.storeVote` while the broker was stepping down from being leader.

> "RaftServer{raft-partition-partition-6} - An uncaught exception occurred, transition to inactive role"

Some logs earlier indicate a potential network partition and this broker (Zeebe-2) was unable to send append requests to Zeebe-0 and Zeebe-1.

The actual reason for the IOException is a bit unclear to me, but atomix tries to write null as its vote into the meta store (internally achieved through a False boolean) where the meta store is a RandomAccessFile.

[Error](https://console.cloud.google.com/errors/CP-hw7q2re2ewAE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1)

**Expected behavior**
The broker should be able to step down without problems.

**Log/Stacktrace**
[Logs](https://console.cloud.google.com/logs/query;query=%0AlogName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22excitingdev%22%0Aresource.labels.namespace_name%3D%2256e7b80b-2daa-4d6f-8148-a03e27896115-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-2%22;timeRange=2020-11-06T08:38:22.507Z%2F2020-11-06T11:38:22.507Z;pinnedLogId=2020-11-06T11:07:52.507879Z%2F5uav8afdywocz?authuser=1&project=camunda-cloud-240911)

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: java.io.IOException: Input/output error
	at io.atomix.storage.buffer.FileBytes.writeByte(FileBytes.java:353) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.buffer.FileBytes.writeByte(FileBytes.java:44) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.buffer.AbstractBytes.writeBoolean(AbstractBytes.java:193) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.buffer.AbstractBytes.writeBoolean(AbstractBytes.java:33) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.buffer.AbstractBuffer.writeBoolean(AbstractBuffer.java:685) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.buffer.AbstractBuffer.writeString(AbstractBuffer.java:886) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.storage.buffer.AbstractBuffer.writeString(AbstractBuffer.java:880) ~[atomix-storage-0.24.2.jar:0.24.2]
	at io.atomix.raft.storage.system.MetaStore.storeVote(MetaStore.java:97) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.impl.RaftContext.setLeader(RaftContext.java:989) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.roles.FollowerRole.schedulePollRequests(FollowerRole.java:272) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.roles.FollowerRole.onHeartbeatTimeout(FollowerRole.java:293) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.raft.roles.FollowerRole.lambda$resetHeartbeatTimeout$4(FollowerRole.java:245) ~[atomix-cluster-0.24.2.jar:0.24.2]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:188) [atomix-utils-0.24.2.jar:0.24.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.IOException: Input/output error
	at java.io.RandomAccessFile.write0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.write(Unknown Source) ~[?:?]
	at java.io.RandomAccessFile.writeByte(Unknown Source) ~[?:?]
	at io.atomix.storage.buffer.FileBytes.writeByte(FileBytes.java:351) ~[atomix-storage-0.24.2.jar:0.24.2]
	... 18 more
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Cluster: excitingdev
 - Namespace: 56e7b80b-2daa-4d6f-8148-a03e27896115-zeebe
 - Zeebe Version: 0.24.2

**Comment by npepinpe** [comment] 2020-11-09 08:54
Even though it's unclear what the root cause is, as we're trying to write to disk here, we should definitely handle IOExceptions instead of just letting it bubble up.

**Comment by npepinpe** [comment] 2021-07-14 14:18
Closing for now as we refactored all this code in the last quarter.

**Closed by npepinpe** 2021-07-14 14:18 UTC
Labels: Scope: broker, Severity: Low, Type: Bug
