### ISSUE TITLE
UserTaskForm should have a default unique id

### ISSUE THREAD

**Issue by Lzgabel** [camunda-cloud/zeebe#8153] opened 2021-11-05 04:20 UTC
**Describe the bug**

UserTaskForm should have a default unique id when use bpmn-model API
```
<extensionElements>
      <ns0:userTaskForm>{}</ns0:userTaskForm>
</extensionElements>
```

**To Reproduce**

Code:
```
BpmnModelInstance done = Bpmn.createProcess("user-task-process").startEvent("start").userTask("user-task-id")
        .zeebeUserTaskForm("{}").endEvent("end-id").done();
```

xml:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" id="definitions_6bf3fa67-9bdd-441a-9ee0-1f1ea9d4c4ba" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="user-task-process">
    <extensionElements>
      <ns0:userTaskForm>{}</ns0:userTaskForm>
    </extensionElements>
    <startEvent id="start" name="start">
      <outgoing>sequenceFlow_6acfba8a-f75a-4825-8109-8ee8ff441fd9</outgoing>
    </startEvent>
    <userTask id="user-task-id" name="user-task-id">
      <extensionElements>
        <ns0:formDefinition formKey="camunda-forms:bpmn:null"/>
      </extensionElements>
      <incoming>sequenceFlow_6acfba8a-f75a-4825-8109-8ee8ff441fd9</incoming>
      <outgoing>sequenceFlow_63d889fd-ef40-4714-b93d-2cbe44b1e483</outgoing>
    </userTask>
    <sequenceFlow id="sequenceFlow_6acfba8a-f75a-4825-8109-8ee8ff441fd9" sourceRef="start" targetRef="user-task-id"/>
    <endEvent id="end-id" name="end-id">
      <incoming>sequenceFlow_63d889fd-ef40-4714-b93d-2cbe44b1e483</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_63d889fd-ef40-4714-b93d-2cbe44b1e483" sourceRef="user-task-id" targetRef="end-id"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_bb4eff62-c7c8-40dd-9c9f-1b56b1b8423f">
    <bpmndi:BPMNPlane bpmnElement="user-task-process" id="BPMNPlane_e1978e34-f4cb-4175-a21e-3290503da002">
      <bpmndi:BPMNShape bpmnElement="start" id="BPMNShape_90438cb7-2e3c-445a-a9cd-cd141a79aa94">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="user-task-id" id="BPMNShape_1982614c-1a9a-495f-9544-030b947ab533">
        <dc:Bounds height="80.0" width="100.0" x="186.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_6acfba8a-f75a-4825-8109-8ee8ff441fd9" id="BPMNEdge_412cb8a5-66ac-481b-a86a-5f9a8b06e680">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="end-id" id="BPMNShape_9919d544-b42f-4976-9900-33a688d8b7f1">
        <dc:Bounds height="36.0" width="36.0" x="336.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_63d889fd-ef40-4714-b93d-2cbe44b1e483" id="BPMNEdge_0fe199dc-5528-4409-bc4c-31f29687b4a4">
        <di:waypoint x="286.0" y="118.0"/>
        <di:waypoint x="336.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>

```

**Expected behavior**

UserTaskForm should have a default unique id.

**Comment by npepinpe** [comment] 2021-11-05 08:17
@korthout - I believe this is a duplicate of what you're working on?

**Comment by korthout** [comment] 2021-11-05 08:36
@npepinpe I don't think this is a duplicate of #8020 which is about a new zeebe extension element (assignmentDefinition). This issue is about adding a default `id` attribute to the already existing zeebe extension element `userTaskForm` when generating it from the model-api.

@Lzgabel Do I understand that correctly? If so, what is your use case for this? Why do you need this?

**Comment by Lzgabel** [comment] 2021-11-05 10:44
Hi @korthout , thanks a lot for quick reply!

> Do I understand that correctly? If so, what is your use case for this? Why do you need this?

Yes.

With the following code, we can find the problem of the same `formkey`:  `'camunda-forms:bpmn:null'`.

code:
```
BpmnModelInstance done = Bpmn.createProcess("user-task-process").startEvent("start").userTask("user-task-id-1")
      .zeebeUserTaskForm("{}").userTask("user-task-id-2")
      .zeebeUserTaskForm("{}").endEvent("end-id").done();
```

xml:

```
<process id="user-task-process">
    <extensionElements>
      <ns0:userTaskForm>{}</ns0:userTaskForm>
      <ns0:userTaskForm>{}</ns0:userTaskForm>
    </extensionElements>
    <userTask id="user-task-id-1" name="user-task-id-1">
      <extensionElements>
        <ns0:formDefinition formKey="camunda-forms:bpmn:null"/>
      </extensionElements>
    </userTask>
    ....
    <userTask id="user-task-id-2" name="user-task-id-2">
      <extensionElements>
        <ns0:formDefinition formKey="camunda-forms:bpmn:null"/>
      </extensionElements>
    </userTask>
    ...
  </process>
```

**Comment by korthout** [comment] 2021-11-05 14:39
@Lzgabel Thanks for sharing this example. I've looked at it in some more detail and I agree that this is a bug. However, a workaround exists with `zeebeUserTaskForm(String id, String form)` which allows you to specify a custom id. Because of this, I'd argue that the severity is low. However, a fix is likely rather simple.

```java
Bpmn.createProcess("user-task-process")
  .startEvent("start")
  .userTask("user-task-id-1")
  .zeebeUserTaskForm("form-1", "{}")
  .userTask("user-task-id-2")
  .zeebeUserTaskForm("form-2", "{}")
  .endEvent("end-id")
  .done();
```

```xml
<process id="user-task-process">
  <extensionElements>
    <ns0:userTaskForm id="form-1">{}</ns0:userTaskForm>
    <ns0:userTaskForm id="form-2">{}</ns0:userTaskForm>
  </extensionElements>
  ...
  <userTask id="user-task-id-1" name="user-task-id-1">
    <extensionElements>
      <ns0:formDefinition formKey="camunda-forms:bpmn:form-1"/>
    </extensionElements>
  </userTask>
  ...
  <userTask id="user-task-id-2" name="user-task-id-2">
    <extensionElements>
      <ns0:formDefinition formKey="camunda-forms:bpmn:form-2"/>
    </extensionElements>
  </userTask>
  ...
</process>
```

**Closed** 2021-11-09 17:44 UTC
Labels: Type: Bug, Severity: Low, Impact: Usability
