### ISSUE TITLE
Elasticsearch exporter is not exporting fast enough

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8728] opened 2022-02-03 10:38 UTC
**Description**

On a large cluster with high load, the elasticsearch exporter cannot keep up which prevents log compaction.

![Screenshot 2022-02-03 at 11-10-50 Zeebe - Grafana](https://user-images.githubusercontent.com/1379753/152326326-a483eba0-5025-4373-a6f3-5ad792ab53fc.png)
![Screenshot 2022-02-03 at 11-13-00 Zeebe - Grafana](https://user-images.githubusercontent.com/1379753/152326354-5562a167-f9dd-47c0-a5b1-3a53fc6b2ba6.png)
![Screenshot 2022-02-03 at 11-14-04 Zeebe - Grafana](https://user-images.githubusercontent.com/1379753/152326373-1f4147ca-bedb-4d30-b692-d4ce33eb7527.png)

Exporter Logs: https://drive.google.com/file/d/1p9s_LxFujh-5t2gVKQWrc4hvsKWUZicZ/view

Elasticsearch does not appear over-utilized: 
![Screenshot 2022-02-03 at 11-40-22 Kubernetes Compute Resources Workload - Grafana](https://user-images.githubusercontent.com/1379753/152327222-e9c043b4-f7a5-4662-8339-b637d0641f0e.png)

**Comment by Zelldon** [comment] 2022-02-03 10:42
Might be duplicate of https://github.com/camunda-cloud/zeebe/issues/6747

**Comment by oleschoenburg** [comment] 2022-02-03 10:45
Oh yeah, that looks very similar :+1:

**Comment by npepinpe** [comment] 2022-02-08 09:53
Closing in favor of #6747, as it seems to me this issue adds new context but describes the same problem.

**Closed by npepinpe** 2022-02-08 09:53 UTC
Labels: Type: Maintenance, Impact: Performance
