### ISSUE TITLE
Flaky BrokerAdminServiceClusterTest#shouldReportPartitionStatusOnFollowersAndLeader

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#8547] opened 2022-01-06 16:46 UTC
**Summary**

- How often does the test fail?
  - at least twice
- Does it block your work?
  - no
- Do we suspect that it is a real failure?
  - Don't think so

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
	at app//io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:133)
	at app//io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:108)
	at app//io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:21)
	at app//io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:196)
	at app//io.camunda.zeebe.broker.Broker.lambda$close$0(Broker.java:170)
	at app//io.camunda.zeebe.broker.Broker$$Lambda$1324/0x0000000100880228.accept(Unknown Source)
	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base@17.0.1/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
	at app//io.camunda.zeebe.broker.Broker.lambda$close$1(Broker.java:168)
	at app//io.camunda.zeebe.broker.Broker$$Lambda$1323/0x0000000100880000.run(Unknown Source)
	at app//io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23)
	at app//io.camunda.zeebe.broker.Broker.close(Broker.java:163)
	at app/zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.lambda$after$3(ClusteringRule.java:259)
	at app/zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule$$Lambda$1784/0x0000000100939480.accept(Unknown Source)
	at java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base@17.0.1/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base@17.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.1/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base@17.0.1/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base@17.0.1/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base@17.0.1/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1223)
	at java.base@17.0.1/java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1915)
	at java.base@17.0.1/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:433)
	at java.base@17.0.1/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:687)
	at java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base@17.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base@17.0.1/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base@17.0.1/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
	at app/zeebe.qa.integration.tests@1.4.0-SNAPSHOT/io.camunda.zeebe.it.clustering.ClusteringRule.after(ClusteringRule.java:256)
</pre>
</details>

**Hypotheses**

Didn't dig into it

**Logs**

[Link to the build](https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/remove-zeebe-test/6/)

[Here's a gist, because the logs were too long :smile:](https://gist.github.com/npepinpe/61c776b50f94fe3fcadd53037f82a682)

**Comment by deepthidevaki** [comment] 2022-02-03 08:05
The following error occurred in Broker 1.
```
15:32:46.372 [Broker-1-StreamProcessor-1] [Broker-1-zb-actors-1] INFO  io.camunda.zeebe.processor - Processor starts replay of events. [snapshot-position: -1, replay-mode: PROCESSING]
15:32:46.373 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] DEBUG io.camunda.zeebe.broker.system - Detected 'HEALTHY' components. The current health status of components: [raft-partition-partition-1{status=HEALTHY}, Broker-1-LogStream-1{status=HEALTHY}, Broker-1-StreamProcessor-1{status=HEALTHY}]
15:32:46.373 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Cancelling transition to LEADER on term 2
15:32:46.373 [Broker-1-StreamProcessor-1] [Broker-1-zb-actors-1] INFO  io.camunda.zeebe.processor - Processor finished replay, with [lastProcessedPosition: -1, lastWrittenPosition: -1]
15:32:46.373 [Broker-1-StreamProcessor-1] [Broker-1-zb-actors-1] DEBUG io.camunda.zeebe.logstreams - Paused processing for partition 1
15:32:46.374 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 2 to INACTIVE
15:32:46.374 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 2 to INACTIVE - preparing ExporterDirector
15:32:46.374 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 2 to INACTIVE - preparing SnapshotDirector
15:32:46.374 [Broker-1-ZeebePartition-1] [Broker-1-zb-actors-0] INFO  io.camunda.zeebe.broker.system - Prepare transition from LEADER on term 2 to INACTIVE - preparing StreamProcessor
15:32:46.375 [Broker-1-StreamProcessor-1] [Broker-1-zb-actors-1] ERROR io.camunda.zeebe.logstreams - Actor Broker-1-StreamProcessor-1 failed in phase STARTED.
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.util.sched.ActorControl.runAtFixedRate(java.time.Duration, java.lang.Runnable)" because "this.actor" is null
	at io.camunda.zeebe.engine.processing.message.PendingProcessMessageSubscriptionChecker.scheduleTimer(PendingProcessMessageSubscriptionChecker.java:69) ~[zeebe-workflow-engine-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.message.PendingProcessMessageSubscriptionChecker.onResumed(PendingProcessMessageSubscriptionChecker.java:64) ~[zeebe-workflow-engine-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.lambda$resumeProcessing$12(StreamProcessor.java:452) ~[zeebe-workflow-engine-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:136) ~[zeebe-util-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
15:32:46.378 [Broker-1-StreamProcessor-1] [Broker-1-zb-actors-1] DEBUG io.camunda.zeebe.util.sched.ActorTask - Discard job io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor$$Lambda$896/0x0000000100645a50 QUEUED from fastLane of Actor Broker-1-StreamProcessor-1.
15:32:46.378 [Broker-1-StreamProcessor-1] [Broker-1-zb-actors-1] DEBUG io.camunda.zeebe.util.sched.ActorTask - Discard job io.camunda.zeebe.util.sched.future.FutureContinuationRunnable QUEUED from fastLane of Actor Broker-1-StreamProcessor-1.

```
Since the StreamProcessor is in failed state, it cannot be closed (It might be also that "close" job is discarded.). As a result closing of the Broker was stuck and timedout.

```
15:33:38.388 [] [Time-limited test] ERROR io.camunda.zeebe.broker.system - Failed to close broker: 
java.util.concurrent.CompletionException: java.lang.InterruptedException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:761) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
```
The brokers are closed in sequence in the test. After the above error, broker 2 is being closed, but the test timed out before the shutdown was completed.

There are multiple things that we should do to resolve this.
1. Root cause the reason for NullPointerException in StreamProcessor. 
2. It should be possible to close an actor even if it is failed.
3. In addition, we can also close the brokers in parallel to speedup the test.

**Closed** 2022-02-11 07:57 UTC
Labels: Type: Unstable Test
