### ISSUE TITLE
Changes of handling corrupted snapshots

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6907] opened 2021-04-29 06:57 UTC
**Description**

Sorry if this is already documented somewhere else, then I was not aware.

I would like to raise the question why we went this way of not starting the follower if the snapshot is corrupted. One of the reasons I'm asking is for documentation purposes **but** also I would like to start a discussion whether we can improve this.

I have the feeling that it is not the optimal approach and makes it worse then before. 

Previous we only detected if we become leader and start the processing that the snapshot is corrupted, t_his we wanted to prevent I assume_. But I'm not 100% sure, what was the issue we wanted to solve here? The leader will step down again, because the snapshot is not valid. Is it because RAFT could potentially already replicate that snapshot again? _If this the case why we not check on become leader whether the checksum is valid?_

With the current approach no partition can start and we can't heal from it without manual intervention, since we not starting the follower we CAN"T get a new snapshot, which was previous the case. 

Could also be that I overseeing something then please point me to it :)

**Comment by korthout** [comment] 2021-04-29 16:30
I also had an idea about this. Just to add to this discussion.

I’d imagine snapshot corruptions don’t happen often. If they do, and are detected, then we could: archive the snapshot, clean out the partition folder, and force restart automatically. If that restart is then successful, we can delete the archived snapshot and continue happily, or otherwise we can fail hard like we do now. I feel like this would lead to a more self-healing system.

**Comment by npepinpe** [comment] 2021-04-29 17:48
What if you start with a corrupted snapshot?

1. You become follower - so far not much happens. You may eventually receive a snapshot which will overwrite it, at which point everything is :ok_hand: 
2. You become follower, and later become leader _before_ receiving a new snapshot. You will fail to maintain leadership (since the processing services cannot be installed), and as such will step down. You may have written new things to the log in the meantime, however, which increases the likelihood that you will become leader in the future (NOTE: this can be mitigated by first checking if the snapshot is valid or not before opening the log stream/log storage appender).
3. You become leader - you will send the snapshot to your followers, however now that we persist snapshot checksums, they will correctly detect your snapshot as corrupted and refuse it. You cannot create a new snapshot as you will not be able to restart from it. You will not be able to start your Zeebe partition in leader role (since you cannot recover your processing services), which will cause you to step down. However, there are very good chances that, as you were leader, you most likely have the longest log, resulting in you becoming leader again. At this point, we're in an election loop since nothing new is going to get written to the log. The one small chance is that you didn't have the longest log, but another follower had the exact same log - then it's a race condition to see when the other follower will get elected. I don't have numbers for this case, but I imagine the chances are slim.

Apart from the case where you start as follower, it looks to me like manual intervention is most likely necessary, since you have a good chance to end up in an election loop, where it's less obvious what the issue is than when you fail on start up with a clear error (though I imagine we could figure out a way to make it more obvious...maybe?).

Full disclosure, I don't really remember being all that involved when we did this, so I'm sure I must be forgetting something - @deepthidevaki can probably provide a better answer :slightly_smiling_face: 

Of course in the long term I'd like that we are self healing, but I'm not sure this is something trivial. I'm happy to discuss here which is the best UX - failing to start, or failing later where it's a bit harder to discover the reason or alert your SREs on it/what to do? One thing to note, once @MiguelPires has finished his topic, it'll probably be good to extend whatever came out of it in terms of handling/observability to the snapshots as well.

**Comment by deepthidevaki** [comment] 2021-04-30 07:09
Thanks @npepinpe You pretty much summed up what I wanted to say.

One additional point is that we also want to detect partially written snapshots and ignore them. If we allow raft to start with corrupted snapshot, it would also start with a partially written snapshot and deletes the older valid snapshots, thus corrupting a perfectly valid state.

Another point. This was not the reason for changing the behavior, but just a side effect. If we build state on the follower this quarter, a follower with a corrupted snapshot is never going to receive a valid snapshot from the leader because the leader is not going to send a snapshot to the follower.

> I would like to raise the question why we went this way of not starting the follower if the snapshot is corrupted.

Note that it is not that we do not start follower. We do not start raft if it has a corrupted state. The same idea that if the log is corrupted, we do not start the cluster irrespective of whether it is a leader or a follower.

> Previous we only detected if we become leader and start the processing that the snapshot is corrupted, t_his we wanted to prevent I assume_. But I'm not 100% sure, what was the issue we wanted to solve here? The leader will step down again, because the snapshot is not valid. 

I'm not sure if this works as expected. In some of my tests the leader successfully started even if it was missing one .sst file. To simulate corruption, I had to remove the MANIFEST file, or remove all .sst files (if I remember correctly). So it is possible that if we start with a corrupted snapshot we continue processing without noticing it or notice it only later. A solution for this would be to verify checksum again on leader startup. But this would delay the failover process further. 

> With the current approach no partition can start and we can't heal from it without manual intervention, since we not starting the follower we CAN"T get a new snapshot, which was previous the case.

I agree it is not a good approach to block all partitions. But the solution for that is not to allow corrupted snapshots. It would be better to make the partitions startup independent. This is not a problem only for corrupted snapshots, but any other case that can block a partition startup - such as log corruption, bugs that cause join process to never complete etc.

**Comment by deepthidevaki** [comment] 2021-04-30 07:10
> I’d imagine snapshot corruptions don’t happen often. If they do, and are detected, then we could: archive the snapshot, clean out the partition folder, and force restart automatically. If that restart is then successful, we can delete the archived snapshot and continue happily, or otherwise we can fail hard like we do now. I feel like this would lead to a more self-healing system.

Never delete data in raft. :) You might end up in data-loss. That is committed events can get lost. However you can do the above steps manually, after checking if it is safe to do it. 
A better approach is for this node to temporarily stay out of leader election until its receives a new valid snapshot and logs, and then participate in election again. https://github.com/camunda-cloud/zeebe/issues/6098#issuecomment-759258932

**Comment by npepinpe** [comment] 2021-04-30 07:12
Thanks for the write-up @deepthidevaki :slightly_smiling_face: 

One idea I had yesterday - we could delay the check until the Raft server starts, but before it transitions from passive to active (initially), so when the server is not in READY state. I think this would allow partitions to start, but would prevent the faulty one from becoming activate (and it would then go back to inactive). This is somewhat a UX issue here, as it's maybe less easy to notice (at the moment) that something is unrecoverable in your broke when it's running as opposed to when it's crash looping.

But I agree, we should work on making partitions start independently anyway.

**Comment by deepthidevaki** [comment] 2021-04-30 07:23
> we could delay the check until the Raft server starts, but before it transitions from passive to active (initially), so when the server is not in READY state. I think this would allow partitions to start, but would prevent the faulty one from becoming activate (and it would then go back to inactive). 

This would work only if the partition startups are independent, right? Currently all partitions have to be ready in raft for atomix cluster to be marked are started.

**Comment by Zelldon** [comment] 2021-04-30 07:26
Thanks folks for your answers. 

@deepthidevaki you wrote:

> A better approach is for this node to temporarily stay out of leader election until its receives a new valid snapshot and logs, and then participate in election again. #6098 (comment)

I think this is similar or a bit what I meant with:

>  If this the case why we not check on become leader whether the checksum is valid?

in the begining. I could imagine that we could have a check on becoming candidate or leader whether my current state is valid (corrupted etc.) and not transition if this is not the case. Does this make sense? It would be similar to we poll before becoming candidate to make sure that others also have currently issues with the current leader.

**Comment by deepthidevaki** [comment] 2021-04-30 10:51
> in the begining. I could imagine that we could have a check on becoming candidate or leader whether my current state is valid (corrupted etc.) and not transition if this is not the case. Does this make sense? It would be similar to we poll before becoming candidate to make sure that others also have currently issues with the current leader.

I guess this will work. A follower does not start election if it knows that it's state is corrupted. :+1:

But it does not completely solve the problem of self-healing. If the node with the corrupted state has the longest log and only one other follower is up, there won't be any leader.  This state is also not easily observable, I guess. In this case we would again need a manual intervention to either bring the other node up or fix the corrupted snapshot in the available follower.

**Comment by Zelldon** [comment] 2021-04-30 14:05
> But it does not completely solve the problem of self-healing. If the node with the corrupted state has the longest log and only one other follower is up, there won't be any leader. This state is also not easily observable, I guess. In this case we would again need a manual intervention to either bring the other node up or fix the corrupted snapshot in the available follower.

This is true, but it enables the case where there is still a leader that it can heal, since new snapshots are replicated to it.

**Comment by Zelldon** [comment] 2021-05-26 12:59
Corrupted snapshots have been seen recently on an incident https://docs.google.com/document/d/1NCO_5NuDcYtFUHg6-SzC768bi-msaDBVy59qWWb6cDM/edit#

**Comment by saig0** [comment] 2021-05-27 03:56
After a problem with unattached volumes, three nodes of three different Camunda cloud clusters had a corrupted snapshot ([incident doc](https://docs.google.com/document/d/1NCO_5NuDcYtFUHg6-SzC768bi-msaDBVy59qWWb6cDM/edit#)). The clusters were healthy but missing one follower. We needed to manually delete the data folders and restart the nodes.

@npepinpe please prioritize the issue. Currently, it requires manual root causing and manual interaction to recover.

**Comment by npepinpe** [comment] 2021-05-27 06:50
This issue was more a question and doesn't really describe the problem. Can you open a different issue describing the problem? Please remember to keep any sensitive info out of the issue - we can use a Google Drive document to collect such things and just link that in the issue itself. We can prioritize that issue then.

**Comment by npepinpe** [comment] 2022-01-21 15:34
Closing for now - other related issues were opened in the mean time and handling of corrupted snapshots was improved in 1.3.

**Closed by npepinpe** 2022-01-21 15:34 UTC
Labels: Type: Question
