### ISSUE TITLE
"main" io.zeebe.client.api.command.ClientStatusException: Method not found: gateway_protocol.Gateway/DeployWorkflow

### ISSUE THREAD

**Issue by nachoroncero** [camunda-cloud/zeebe#7252] opened 2021-06-10 17:46 UTC
Hello,

I have been many hours trying to star working with Zeebe but there is always an issue.

Now, I created a BPMN file with my orders and just wanted to deploy it, but I have that  error.:

on in thread "main" io.zeebe.client.api.command.ClientStatusException: Method not found: gateway_protocol.Gateway/DeployWorkflow
	at io.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
	at io.zeebe.App.main(App.java:21)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: gateway_protocol.Gateway/DeployWorkflow
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
	... 1 more
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: gateway_protocol.Gateway/DeployWorkflow
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

**Comment by Zelldon** [comment] 2021-06-10 18:18
Based on the exception I assume you have a 1.0 Zeebe cluster but using an older client, e.g. 0.26.x. Is this the case?

**Comment by nachoroncero** [comment] 2021-06-10 21:06
I changed that and now the exception is different. I changed the version of
the project to 0.26.0 because if I change the version of the dependency to
1.0.0 says it does not exist. Thanks for your help

Connected.
Exception in thread "main"
io.zeebe.client.api.command.ClientStatusException: io exception
at
io.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
at
io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
at io.zeebe.App.main(App.java:21)
Caused by: java.util.concurrent.ExecutionException:
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at
java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
at
java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
at
io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
... 1 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at io.grpc.Status.asRuntimeException(Status.java:533)
at
io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
at
io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
at
io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
at
io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
at
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
at
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException:
Connection refused: no further information: /127.0.0.1:26500
Caused by: java.net.ConnectException: Connection refused: no further
information
at java.base/sun.nio.ch.Net.pollConnect(Native Method)
at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)

**Comment by Zelldon** [comment] 2021-06-11 05:21
> I changed that and now the exception is different. I changed the version of
the project to 0.26.0 because if I change the version of the dependency to
1.0.0 says it does not exist. Thanks for your help

Hey @nachoroncero I think the issue here is that you don't have the dependency not locally, which is some IDE's then complain first that this doesn't exist. Simplest would be to do a `mvn clean install` on you project. Or in intellij you can import dependencies in the maven window, see here https://www.jetbrains.com/help/idea/work-with-maven-dependencies.html#maven_import_dependency. 

So I suggest you try it again with 1.0 client dependency, since 0.26 will not work with a 1.0 zeebe cluster. The versions are not compatible. 

Hope that helps.

Best Regards
Chris

**Comment by nachoroncero** [comment] 2021-06-11 07:25
Hello Chris,

Is this what you want me to change? Because I'm doing it and still says
that dependency cannot be found.

<dependencies>
  <dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>3.8.1</version>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>io.zeebe</groupId>
    <artifactId>zeebe-client-java</artifactId>
    <version>1.0</version> /*THIS LINE??*/ BECAUSE INTELLIJ SAYS THIS
DOESN`T EXISTS
  </dependency>

**Comment by Zelldon** [comment] 2021-06-11 07:29
Hey @nachoroncero 

yeah the issue is that we had to change also the group id.

It is now:

```
  <dependency>
    <groupId>io.camunda</groupId>
    <artifactId>zeebe-client-java</artifactId>
    <version>1.0</version>
  </dependency>
```

Greets
Chris

**Comment by nachoroncero** [comment] 2021-06-11 07:38
Hi,

Does it exist? Because I try to upload it with intellij and then used the
maven clean install and:

Failed to execute goal on project zeebe-get-started-java-client: Could not
resolve dependencies for project io.zeebe:zeebe-get-started-java-clie
nt:jar:1.0-SNAPSHOT: io.camunda:zeebe-client-java:jar:1.0 was not found in
https://repo.maven.apache.org/maven2 during a previous attempt.

**Comment by npepinpe** [comment] 2021-06-15 08:01
The older getting started guide were replaced for Camunda Cloud specific guides and haven't been updated unfortunately. This is the new [getting started guide](https://github.com/camunda-cloud/camunda-cloud-get-started), but like I said it's very Camunda Cloud specific, not really for on-prem/bare-metal deployment. So there is no 1.0 version of the getting started projects, but you can still use the client correctly. 

I see you had more help in other issues - should we close this issue for now?

**Comment by npepinpe** [comment] 2021-06-15 08:07
Ah, it seems the new guide has a section for local development - see [here](https://github.com/camunda-cloud/camunda-cloud-get-started#local-setup)

**Comment by nachoroncero** [comment] 2021-06-15 08:12
Ok, thank you.

Then, if I want to choose the 1.0 version and Docker it isn’t available yet
or what?

I need to use Docker and Java as Client… can you send me the link to
download a previous version of Zeebe for docker-compose?

Thank you again

**Comment by morphace** [comment] 2021-06-17 16:38
Hi,

I have the same issue if:
1.) I try to run the simple monitor docker-compose (master branch) from the zeebe-docker-compose project
2.) I try to deploy a workflow with the most recent version of the Go client (which is 0.26.0?)

Anyone who can help here?

Thanks

**Comment by jwulf** [comment] 2021-07-30 01:55
You need to use a 0.26 compatible client with 0.26 brokers and a 1.x-compatible client with 1.x brokers. The major version is a breaking change.

So check your broker and client major versions match. For further questions, please open a topic on the forum: [https://forum.camunda.io](https://forum.camunda.io).

**Closed by jwulf** 2021-07-30 01:55 UTC
Labels: Type: Question
