### ISSUE TITLE
Reusing of StreamWriter in TimerTrigger is causing weird source record positions

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6954] opened 2021-05-04 06:30 UTC
**Describe the bug**

In the compact log view we see that the Timer.TRIGGER is caused by an XOR ACTIVATE command, which doesn't make sense.

```
E PROC_INST          SEQ_FLOW_TAKEN - #22->#19 K10 - SEQUENCE_FLOW "sequenc..9cb6481" in <process "process1"[K05]>
C PROC_INST          ACTIVATE       - #23->#19 K11 - EXCLUSIVE_GATEWAY "xor" in <process "process1"[K05]>
E PROC_INST          ACTIVATING     - #24->#23 K11 - EXCLUSIVE_GATEWAY "xor" in <process "process1"[K05]>
E INCIDENT           CREATED        - #25->#23 K12 - EXTRACT_VALUE_ERROR failed to evaluate expression 'foo < 5': ValError(no variable found for name 'foo') is not comparable,  @"xor"[K11] in <process "process1"[K05]>
C TIMER              TRIGGER        - #26->#23 K08 -  @"startEv..b884dee"[K05]  in <process "K03"[K05]> due T08:22:52.686
C TIMER              TRIGGER        - #27->#23 K07 -  @"startEv..1b3fe8f"[K05]  in <process "K03"[K05]> due T08:23:06.685
E TIMER              TRIGGERED      - #28->#26 K08 -  @"startEv..b884dee"[K05]  in <process "K03"[K05]> due T08:22:52.686
```

If we take a look at the CompactLoggerCode we see that it uses the sourceRecordLogPositions of the record, so this seems to be set wrong? https://github.com/camunda-cloud/zeebe/blob/develop/test-util/src/main/java/io/camunda/zeebe/test/util/record/CompactRecordLogger.java#L219

**To Reproduce**

You can use this failing test to cause this output:
```
 @Test
  public void shouldCredasateIncidentIfExclusiveGatewayHasNoMatchingCondition() {
    // given
    final var process = Bpmn.createExecutableProcess("process1");

    process
        .eventSubProcess("eventSub")
        .startEvent()
        .interrupting(false)
        //        .interrupting(true)
        .timerWithDuration("PT15S")
        .endEvent();

    process
        .eventSubProcess("eventSub2")
        .startEvent()
        .interrupting(false)
        //        .interrupting(true)
        .timerWithDuration("PT1S")
        .endEvent();

    final var modelInstance =
        process
            .startEvent()
            .exclusiveGateway("xor")
            .sequenceFlowId("s1")
            .conditionExpression("foo < 5")
            .endEvent()
            .done();

    ENGINE.deployment().withXmlResource(modelInstance).deploy();

    final long processInstanceKey = ENGINE.processInstance().ofBpmnProcessId("process1").create();

    RecordingExporter.incidentRecords()
        .withProcessInstanceKey(processInstanceKey)
        .withIntent(IncidentIntent.CREATED)
        .await();

    // when
    ENGINE.increaseTime(Duration.ofMinutes(12));

    // then
    RecordingExporter.processInstanceRecords()
        .withProcessInstanceKey(processInstanceKey)
        .withElementId("eventSub")
        .withIntent(ProcessInstanceIntent.ELEMENT_COMPLETED)
        .withElementType(BpmnElementType.EVENT_SUB_PROCESS)
        .await();

    RecordingExporter.processInstanceRecords()
        .withProcessInstanceKey(processInstanceKey)
        .withElementType(BpmnElementType.PROCESS)
        .withIntent(ProcessInstanceIntent.ELEMENT_COMPLETED)
        .await();
  }
```

**Expected behavior**
The source record position is not set at all.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
08:22:51.626 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@2e56aa86)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@67f913af, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@39178cb7, configuration: Configuration(false)]
08:22:56.785 [] INFO  io.zeebe.test - Test failed, following records were exported:
08:22:56.945 [] INFO  io.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DEPLOYMENT         CREATE         - #05-> -1  -1 - 
E PROC               CREATED        - #06->#05 K03 - process.xml->"process1" (version:1)
E DEPLOYMENT         CREATED        - #07->#05 K04 - process.xml
E DEPLOYMENT         FULLY_DISTR    - #08->#05 K04 - 
C PROC_INST_CREATION CREATE         - #09-> -1  -1 - new <process "process1"> (no vars)
C PROC_INST          ACTIVATE       - #10->#09 K05 - PROCESS "process1" in <process "process1"[K05]>
E PROC_INST_CREATION CREATED        - #11->#09 K06 - new <process "process1"> (no vars)
E PROC_INST          ACTIVATING     - #12->#10 K05 - PROCESS "process1" in <process "process1"[K05]>
E TIMER              CREATED        - #13->#10 K07 -  @"startEv..1b3fe8f"[K05]  in <process "K03"[K05]> due T08:23:06.685
E TIMER              CREATED        - #14->#10 K08 -  @"startEv..b884dee"[K05]  in <process "K03"[K05]> due T08:22:52.686
E PROC_INST          ACTIVATED      - #15->#10 K05 - PROCESS "process1" in <process "process1"[K05]>
C PROC_INST          ACTIVATE       - #16->#10  -1 - START_EVENT "startEv..a501ff4" in <process "process1"[K05]>
E PROC_INST          ACTIVATING     - #17->#16 K09 - START_EVENT "startEv..a501ff4" in <process "process1"[K05]>
E PROC_INST          ACTIVATED      - #18->#16 K09 - START_EVENT "startEv..a501ff4" in <process "process1"[K05]>
C PROC_INST          COMPLETE       - #19->#16 K09 - START_EVENT "startEv..a501ff4" in <process "process1"[K05]>
E PROC_INST          COMPLETING     - #20->#19 K09 - START_EVENT "startEv..a501ff4" in <process "process1"[K05]>
E PROC_INST          COMPLETED      - #21->#19 K09 - START_EVENT "startEv..a501ff4" in <process "process1"[K05]>
E PROC_INST          SEQ_FLOW_TAKEN - #22->#19 K10 - SEQUENCE_FLOW "sequenc..9cb6481" in <process "process1"[K05]>
C PROC_INST          ACTIVATE       - #23->#19 K11 - EXCLUSIVE_GATEWAY "xor" in <process "process1"[K05]>
E PROC_INST          ACTIVATING     - #24->#23 K11 - EXCLUSIVE_GATEWAY "xor" in <process "process1"[K05]>
E INCIDENT           CREATED        - #25->#23 K12 - EXTRACT_VALUE_ERROR failed to evaluate expression 'foo < 5': ValError(no variable found for name 'foo') is not comparable,  @"xor"[K11] in <process "process1"[K05]>
C TIMER              TRIGGER        - #26->#23 K08 -  @"startEv..b884dee"[K05]  in <process "K03"[K05]> due T08:22:52.686
C TIMER              TRIGGER        - #27->#23 K07 -  @"startEv..1b3fe8f"[K05]  in <process "K03"[K05]> due T08:23:06.685
E TIMER              TRIGGERED      - #28->#26 K08 -  @"startEv..b884dee"[K05]  in <process "K03"[K05]> due T08:22:52.686
E PROC_EVNT          TRIGGERING     - #29->#26 K13 -  @"startEv..b884dee"[K05] in <process K03[K05]> (no vars)
E PROC_EVNT          TRIGGERED      - #30->#26 K13 -  @"startEv..b884dee"[K05] in <process K03[K05]> (no vars)
E PROC_INST          ACTIVATING     - #31->#26 K14 - EVENT_SUB_PROCESS "eventSub2" in <process "process1"[K05]>
E PROC_INST          ACTIVATED      - #32->#26 K14 - EVENT_SUB_PROCESS "eventSub2" in <process "process1"[K05]>
C PROC_INST          ACTIVATE       - #33->#26  -1 - START_EVENT "startEv..b884dee" in <process "process1"[K05]>
E TIMER              TRIGGERED      - #34->#27 K07 -  @"startEv..1b3fe8f"[K05]  in <process "K03"[K05]> due T08:23:06.685
E PROC_EVNT          TRIGGERING     - #35->#27 K15 -  @"startEv..1b3fe8f"[K05] in <process K03[K05]> (no vars)
E PROC_EVNT          TRIGGERED      - #36->#27 K15 -  @"startEv..1b3fe8f"[K05] in <process K03[K05]> (no vars)
E PROC_INST          ACTIVATING     - #37->#27 K16 - EVENT_SUB_PROCESS "eventSub" in <process "process1"[K05]>
E PROC_INST          ACTIVATED      - #38->#27 K16 - EVENT_SUB_PROCESS "eventSub" in <process "process1"[K05]>
C PROC_INST          ACTIVATE       - #39->#27  -1 - START_EVENT "startEv..1b3fe8f" in <process "process1"[K05]>
E PROC_INST          ACTIVATING     - #40->#33 K17 - START_EVENT "startEv..b884dee" in <process "process1"[K05]>
E PROC_INST          ACTIVATED      - #41->#33 K17 - START_EVENT "startEv..b884dee" in <process "process1"[K05]>
C PROC_INST          COMPLETE       - #42->#33 K17 - START_EVENT "startEv..b884dee" in <process "process1"[K05]>
E PROC_INST          ACTIVATING     - #43->#39 K18 - START_EVENT "startEv..1b3fe8f" in <process "process1"[K05]>
E PROC_INST          ACTIVATED      - #44->#39 K18 - START_EVENT "startEv..1b3fe8f" in <process "process1"[K05]>
C PROC_INST          COMPLETE       - #45->#39 K18 - START_EVENT "startEv..1b3fe8f" in <process "process1"[K05]>
E PROC_INST          COMPLETING     - #46->#42 K17 - START_EVENT "startEv..b884dee" in <process "process1"[K05]>
E PROC_INST          COMPLETED      - #47->#42 K17 - START_EVENT "startEv..b884dee" in <process "process1"[K05]>
E PROC_INST          SEQ_FLOW_TAKEN - #48->#42 K19 - SEQUENCE_FLOW "sequenc..45a02a8" in <process "process1"[K05]>
C PROC_INST          ACTIVATE       - #49->#42 K20 - END_EVENT "endEven..0f4e936" in <process "process1"[K05]>
E PROC_INST          COMPLETING     - #50->#45 K18 - START_EVENT "startEv..1b3fe8f" in <process "process1"[K05]>
E PROC_INST          COMPLETED      - #51->#45 K18 - START_EVENT "startEv..1b3fe8f" in <process "process1"[K05]>
E PROC_INST          SEQ_FLOW_TAKEN - #52->#45 K21 - SEQUENCE_FLOW "sequenc..e950142" in <process "process1"[K05]>
C PROC_INST          ACTIVATE       - #53->#45 K22 - END_EVENT "endEven..9445fbc" in <process "process1"[K05]>
E PROC_INST          ACTIVATING     - #54->#49 K20 - END_EVENT "endEven..0f4e936" in <process "process1"[K05]>
E PROC_INST          ACTIVATED      - #55->#49 K20 - END_EVENT "endEven..0f4e936" in <process "process1"[K05]>
E PROC_INST          COMPLETING     - #56->#49 K20 - END_EVENT "endEven..0f4e936" in <process "process1"[K05]>
E PROC_INST          COMPLETED      - #57->#49 K20 - END_EVENT "endEven..0f4e936" in <process "process1"[K05]>
C PROC_INST          COMPLETE       - #58->#49 K14 - EVENT_SUB_PROCESS "eventSub2" in <process "process1"[K05]>
E PROC_INST          ACTIVATING     - #59->#53 K22 - END_EVENT "endEven..9445fbc" in <process "process1"[K05]>
E PROC_INST          ACTIVATED      - #60->#53 K22 - END_EVENT "endEven..9445fbc" in <process "process1"[K05]>
E PROC_INST          COMPLETING     - #61->#53 K22 - END_EVENT "endEven..9445fbc" in <process "process1"[K05]>
E PROC_INST          COMPLETED      - #62->#53 K22 - END_EVENT "endEven..9445fbc" in <process "process1"[K05]>
C PROC_INST          COMPLETE       - #63->#53 K16 - EVENT_SUB_PROCESS "eventSub" in <process "process1"[K05]>
E PROC_INST          COMPLETING     - #64->#58 K14 - EVENT_SUB_PROCESS "eventSub2" in <process "process1"[K05]>
E PROC_INST          COMPLETED      - #65->#58 K14 - EVENT_SUB_PROCESS "eventSub2" in <process "process1"[K05]>
E PROC_INST          COMPLETING     - #66->#63 K16 - EVENT_SUB_PROCESS "eventSub" in <process "process1"[K05]>
E PROC_INST          COMPLETED      - #67->#63 K16 - EVENT_SUB_PROCESS "eventSub" in <process "process1"[K05]>

-------------- Deployed Processes ----------------------
process.xml ------ 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="definitions_009617ad-e145-4f41-83c1-3ac1e5a51f09" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process1" isExecutable="true">
    <subProcess id="eventSub" name="eventSub" triggeredByEvent="true">
      <startEvent id="startEvent_3522d6dc-ff48-417d-b382-ad27a1b3fe8f" isInterrupting="false">
        <outgoing>sequenceFlow_c447853a-1d8d-4cc5-908a-e57cae950142</outgoing>
        <timerEventDefinition id="timerEventDefinition_b535d8e9-41d2-4761-be16-d09982cfd4aa">
          <timeDuration id="timeDuration_c1e2fb52-dcc1-4952-af53-28cbe1bfd0fb">PT15S</timeDuration>
        </timerEventDefinition>
      </startEvent>
      <endEvent id="endEvent_0b4708ee-df91-4688-ba26-ec64b9445fbc">
        <incoming>sequenceFlow_c447853a-1d8d-4cc5-908a-e57cae950142</incoming>
      </endEvent>
      <sequenceFlow id="sequenceFlow_c447853a-1d8d-4cc5-908a-e57cae950142" sourceRef="startEvent_3522d6dc-ff48-417d-b382-ad27a1b3fe8f" targetRef="endEvent_0b4708ee-df91-4688-ba26-ec64b9445fbc"/>
    </subProcess>
    <subProcess id="eventSub2" name="eventSub2" triggeredByEvent="true">
      <startEvent id="startEvent_667617e8-d6f3-42ae-a76a-9165cb884dee" isInterrupting="false">
        <outgoing>sequenceFlow_5e046348-2cf0-47a2-9503-c5c6045a02a8</outgoing>
        <timerEventDefinition id="timerEventDefinition_b556ada0-3fb1-4957-a34b-084498801587">
          <timeDuration id="timeDuration_bbd3e8f4-ec98-4bbe-aa26-4c20786c2bd1">PT1S</timeDuration>
        </timerEventDefinition>
      </startEvent>
      <endEvent id="endEvent_29ee17b5-04c3-451b-8d9d-789c90f4e936">
        <incoming>sequenceFlow_5e046348-2cf0-47a2-9503-c5c6045a02a8</incoming>
      </endEvent>
      <sequenceFlow id="sequenceFlow_5e046348-2cf0-47a2-9503-c5c6045a02a8" sourceRef="startEvent_667617e8-d6f3-42ae-a76a-9165cb884dee" targetRef="endEvent_29ee17b5-04c3-451b-8d9d-789c90f4e936"/>
    </subProcess>
    <startEvent id="startEvent_be84841a-8ebe-4945-8955-cb88fa501ff4">
      <outgoing>sequenceFlow_b23647d2-611c-45b7-a21f-741cc9cb6481</outgoing>
    </startEvent>
    <exclusiveGateway id="xor" name="xor">
      <incoming>sequenceFlow_b23647d2-611c-45b7-a21f-741cc9cb6481</incoming>
      <outgoing>s1</outgoing>
    </exclusiveGateway>
    <sequenceFlow id="sequenceFlow_b23647d2-611c-45b7-a21f-741cc9cb6481" sourceRef="startEvent_be84841a-8ebe-4945-8955-cb88fa501ff4" targetRef="xor"/>
    <sequenceFlow id="s1" sourceRef="xor" targetRef="endEvent_2aba879b-95e5-497a-b827-9a0f9c26f5df">
      <conditionExpression id="conditionExpression_28429f9a-af74-4952-902d-94280fada8fd">=foo &lt; 5</conditionExpression>
    </sequenceFlow>
    <endEvent id="endEvent_2aba879b-95e5-497a-b827-9a0f9c26f5df">
      <incoming>s1</incoming>
    </endEvent>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_3bda141b-d7ad-47ec-a567-a1b2e00e8c47">
    <bpmndi:BPMNPlane bpmnElement="process1" id="BPMNPlane_9e268020-1776-4f51-a4d6-ab4a5c692c65">
      <bpmndi:BPMNShape bpmnElement="eventSub" id="BPMNShape_fba1fc45-da16-4e04-ba51-899e665c7ed9" isExpanded="true">
        <dc:Bounds height="200.0" width="350.0" x="100.0" y="250.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="startEvent_3522d6dc-ff48-417d-b382-ad27a1b3fe8f" id="BPMNShape_685bc08a-433e-4922-a724-0b36ad34a026">
        <dc:Bounds height="36.0" width="36.0" x="150.0" y="332.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endEvent_0b4708ee-df91-4688-ba26-ec64b9445fbc" id="BPMNShape_9cb12b1e-88be-4f7e-85e4-45ed201c8edd">
        <dc:Bounds height="36.0" width="36.0" x="236.0" y="332.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_c447853a-1d8d-4cc5-908a-e57cae950142" id="BPMNEdge_4721f2aa-c790-4bad-973d-446e721f7296">
        <di:waypoint x="186.0" y="350.0"/>
        <di:waypoint x="236.0" y="350.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="eventSub2" id="BPMNShape_b915333c-3d14-43d1-a396-68de6e146a54" isExpanded="true">
        <dc:Bounds height="200.0" width="350.0" x="100.0" y="500.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="startEvent_667617e8-d6f3-42ae-a76a-9165cb884dee" id="BPMNShape_207498d9-ad1e-4698-860a-af4722d5ad31">
        <dc:Bounds height="36.0" width="36.0" x="150.0" y="582.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endEvent_29ee17b5-04c3-451b-8d9d-789c90f4e936" id="BPMNShape_8867a608-a275-4cd8-ac41-cb9da907172e">
        <dc:Bounds height="36.0" width="36.0" x="236.0" y="582.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_5e046348-2cf0-47a2-9503-c5c6045a02a8" id="BPMNEdge_47cb8d97-71a8-4805-8ce3-b963979c781e">
        <di:waypoint x="186.0" y="600.0"/>
        <di:waypoint x="236.0" y="600.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="startEvent_be84841a-8ebe-4945-8955-cb88fa501ff4" id="BPMNShape_bdf867fd-9652-4aa7-a526-7af6a01ff368">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="xor" id="BPMNShape_51e3f2b2-6eb7-4631-aa59-fc768c700088" isMarkerVisible="true">
        <dc:Bounds height="50.0" width="50.0" x="186.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_b23647d2-611c-45b7-a21f-741cc9cb6481" id="BPMNEdge_81d97bcd-cef9-45fe-8730-43f9c29b7bc9">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="endEvent_2aba879b-95e5-497a-b827-9a0f9c26f5df" id="BPMNShape_063e92af-3182-4bf4-b680-c33074200de5">
        <dc:Bounds height="36.0" width="36.0" x="286.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="s1" id="BPMNEdge_89f41484-cd89-4169-9eeb-5f7c76761f5a">
        <di:waypoint x="236.0" y="118.0"/>
        <di:waypoint x="286.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>

--------------- Decomposed keys (for debugging) -----------------
 -1 <-> -1
K03 <-> 2251799813685251
K04 <-> 2251799813685252
K05 <-> 2251799813685253
K06 <-> 2251799813685254
K07 <-> 2251799813685255
K08 <-> 2251799813685256
K09 <-> 2251799813685257
K10 <-> 2251799813685258
K11 <-> 2251799813685259
K12 <-> 2251799813685260
K13 <-> 2251799813685261
K14 <-> 2251799813685262
K15 <-> 2251799813685263
K16 <-> 2251799813685264
K17 <-> 2251799813685265
K18 <-> 2251799813685266
K19 <-> 2251799813685267
K20 <-> 2251799813685268
K21 <-> 2251799813685269
K22 <-> 2251799813685270


io.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria

	at io.zeebe.test.util.stream.StreamWrapper.await(StreamWrapper.java:72)
	at io.zeebe.engine.processing.incident.ConditionIncidentTest.shouldCredasateIncidentIfExclusiveGatewayHasNoMatchingCondition(ConditionIncidentTest.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

**Comment by npepinpe** [comment] 2021-05-04 06:31
Duplicate of https://github.com/camunda-cloud/zeebe/issues/5420 ?

**Closed** 2021-05-04 07:52 UTC
Labels: Scope: broker, Severity: Low, Status: Needs Priority, Type: Bug
