### ISSUE TITLE
DiskSpaceRecoveryClusteredTest.lambda$shouldCorrelateMessageAfterDiskSpaceAvailableAgain flaky

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#5130] opened 2020-08-07 09:41 UTC
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
io.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:77)
	at io.zeebe.broker.it.util.ZeebeAssertHelper.assertWorkflowInstanceCompleted(ZeebeAssertHelper.java:67)
	at io.zeebe.broker.it.util.ZeebeAssertHelper.assertWorkflowInstanceCompleted(ZeebeAssertHelper.java:77)
	at io.zeebe.broker.it.health.DiskSpaceRecoveryClusteredTest.lambda$shouldCorrelateMessageAfterDiskSpaceAvailableAgain$4(DiskSpaceRecoveryClusteredTest.java:124)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
</pre>
</details>

**Hypotheses**

**Logs**

<details><summary>Logs</summary>

[TEST-io.zeebe.broker.it.health.DiskSpaceRecoveryClusteredTest-it.zip](https://github.com/zeebe-io/zeebe/files/5040571/TEST-io.zeebe.broker.it.health.DiskSpaceRecoveryClusteredTest-it.zip)

**Comment by deepthidevaki** [comment] 2020-08-19 13:22
I couldn't reproduce the failures. But from the logs the workflow instance was completed. So I think it is only a timing issue. `assertWorkflowInstanceCompleted` throws an exception when it couldn't find the necessary workflow instead of retrying. 

```
09:40:33.359 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":4503599627370497,"position":30,"timestamp":1596706890070,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":2,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"bpmnProcessId":"process1","workflowKey":2251799813685249,"workflowInstanceKey":4503599627370497,"elementId":"process1","flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1},"sourceRecordPosition":29}

09:40:33.360 [] [Time-limited test] INFO  io.zeebe.test.records - {"valueType":"WORKFLOW_INSTANCE","key":2251799813685251,"position":52,"timestamp":1596706890153,"recordType":"EVENT","intent":"ELEMENT_COMPLETED","partitionId":1,"rejectionType":"NULL_VAL","rejectionReason":"","value":{"version":1,"bpmnProcessId":"process1","workflowKey":2251799813685249,"workflowInstanceKey":2251799813685251,"elementId":"process1","flowScopeKey":-1,"bpmnElementType":"PROCESS","parentWorkflowInstanceKey":-1,"parentElementInstanceKey":-1},"sourceRecordPosition":51}
```

**Comment by npepinpe** [comment] 2021-03-22 10:01
Happened again: https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/6177-timer-created/18/tests

Looks like publishing the last message times out, though it''s unclear why.

**Comment by npepinpe** [comment] 2021-07-04 15:21
We can now track flakiness of tests individually via the build result dashboard. I'm closing these issues and we can reopen as we see them occur.

**Closed** 2021-07-04 15:21 UTC
Labels: Release: 0.25.0, Release: 0.25.0-alpha2, Type: Unstable Test
