### ISSUE TITLE
Buffered messages are correlated only once per process

### ISSUE THREAD

**Issue by RedUno** [camunda-cloud/zeebe#7205] opened 2021-06-07 09:36 UTC
**Describe the bug**
I have a process containing a receive task ase bellow
![image](https://user-images.githubusercontent.com/6310155/120990369-c3398480-c780-11eb-8139-e53cc2532bbf.png)

If a message is buffered, and multiple instances of the same process are created while the message is still buffered, only the first instance is correlated, the others subscriptions are stuck at Created state .  

**To Reproduce**

1. Deploy the following process [test_event_ttl.zip](https://github.com/camunda-cloud/zeebe/files/6607620/test_event_ttl.zip)
2. publish a message with TTL > 0 
`zbctl publish message Test --correlationKey 1234 --ttl '60s' --insecure`
3. Create an instance (_intance_1_)
`zbctl create instance Test_TTL --variables '{"imei": "1234"}' --insecure`
4. Create a second instance (_intance_2_)
`zbctl create instance Test_TTL --variables '{"imei": "1234"}' --insecure`

_intance_1_ is completed, _intance_2_ still waiting for a message to be correlated.

**Expected behavior**
the buffered message should be correlated with any created instance while the message is still alive. 
_intance_2_ should consume the message and complete the receive task.

**Environment:**
 - OS: Linux
 - Zeebe Version: 1.0.0

**Comment by saig0** [comment] 2021-06-07 11:38
Hi @RedUno,

thank you for raising this up. But the described behavior is expected. Please have a look at the docs: https://docs.camunda.io/docs/product-manuals/concepts/messages#message-cardinality

If the message would be correlated multiple times to a process or process instance then you may end up in loops or unintended processing of the same message multiple times.

If you share more about your use case then I can try to point you in the right direction.

**Comment by RedUno** [comment] 2021-06-07 13:39
Hi @saig0,
Thank you for the answer & the documentation, i was experimenting with buffered messages feature and came across this use case. it's clearer to me now why i had this behavior.

**Comment by RedUno** [comment] 2021-06-08 07:52
Hi @saig0,
I have i use case where i don't understand the engine behaviour if you could explain to me please.
I have the following Process:

![image](https://user-images.githubusercontent.com/6310155/121142134-fab93700-c83b-11eb-9d9a-3979c37e397d.png)

I send a request to a device, the device responds quickly with a buffered message, if the message is received before the subscription is opened, the response will be lost and ignored.   

I can reproduce the use case using timer as below:
![image](https://user-images.githubusercontent.com/6310155/121137754-487f7080-c837-11eb-808e-d54948ba465d.png)

[test_event_ttl.zip](https://github.com/camunda-cloud/zeebe/files/6614524/test_event_ttl.zip)

then:

1. create an instance: `zbctl create instance Test_TTL --variables '{"imei": "1234"}' --insecure`
2. publish message: `zbctl publish message Test --correlationKey 1234 --ttl '60s' --insecure`

If i invert the order by 

1. publishing message: `zbctl publish message Test --correlationKey 1234 --ttl '60s' --insecure`
2. create an instance: `zbctl create instance Test_TTL --variables '{"imei": "1234"}' --insecure`
the message will be correlated.

From my point of view these two scenarios should behave the same way and the message should be correlated.
am i doing something wrong ?  
Is there a way to ensure that the received message will not be lost ? 
I can use a parallel flow and open the subscription before sending the request, but if the device doesn't respond to my request the instance will never complete. adding a timeout to receive task will fix this issue but it's difficult for me to define timeout value, it my take milliseconds before receiving response as it may take days.

Thank you

**Comment by saig0** [comment] 2021-06-08 13:28
@RedUno thank you for sharing the example.

Your expectation is correct. The message should be buffered and correlated to the receive task.

I tried to reproduce the behavior but it works for me. If I publish the message before creating the instance then the message is still correlated (as expected).

Please make sure that you start with a clean state. Maybe, there is another running process instance of this process and the message is correlated to the other instance.

**Comment by RedUno** [comment] 2021-06-09 07:35
Hi @saig0,
Yes, you were right. It behave as expected when starting from a clean state. 
I thank you for your time and reactivity.

**Comment by saig0** [comment] 2021-06-09 08:26
I close the issue because the question is answered :heavy_check_mark:

**Closed by saig0** 2021-06-09 08:26 UTC
Labels: Type: Question
