### ISSUE TITLE
The metric `Number of records not exported` is incorrect.

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#8127] opened 2021-11-03 08:12 UTC
**Describe the bug**

The value for number of not exported records is too high. But those partitions have only one log segment left. This might look as if we compact before exporting. But I'm pretty sure that is not the case, instead the metrics is visualized incorrectly.

![image](https://user-images.githubusercontent.com/1997478/140025512-f4b546ba-478b-4cf7-896c-73f513bd1caf.png)

I think this happens, because of leader changes and the both old leader and new leader have different values for the exported position/processed position.

The current query is as follows
`
sum (zeebe_log_appender_last_committed_position{namespace=~"$namespace", partition=~"$partition"}) by (partition) - sum (zeebe_exporter_last_exported_position{namespace=~"$namespace", partition=~"$partition", exporter="elasticsearch"}) by (partition)
`
I think using `sum` here is the problem. Instead may be using `max` works. `max` will always return the values from the leader. So that will be more accurate. When using sum, we are adding position from both leader and followers which is incorrect.

Looking at the other metrics - Last processed position, Last appended position, etc is also using sum, which is also incorrect, I think.

**To Reproduce**

Not sure how to verify if the value is correct. But we can may be look at the metrics from the benchmark clusters and compare it with the actual values from the brokers.

**Comment by Zelldon** [comment] 2021-11-03 08:17
Maybe duplicate of https://github.com/camunda-cloud/zeebe/issues/7228

**Closed** 2021-11-03 08:35 UTC
Labels: Type: Bug, Severity: Low, Impact: Observability
