### ISSUE TITLE
Zeebe Java Client can not be used to build Native Image with GraalVM

### ISSUE THREAD

**Issue by rezanirumand** [camunda-cloud/zeebe#6054] opened 2021-01-04 09:55 UTC
**Describe the bug**
When Including the Zeebe Java Client in a Quarkus based Project and trying to build native image, build fails due to a dependency of zeebe client. I understand this might be a configuration issue, but I could not solve it as of now. Appreciate the help:

**To Reproduce**

1) clone the repository `https://github.com/rezanirumand/order-service-zeebe`
2) With installed GraalVM  `mvnw clean package -DskipTests -Pnative`
or
2) Build in container  `mvnw package -Pnative -Dquarkus.native.container-build=true`

**Expected behavior**
Native Image build is successful. 

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledHeapByteBuf
io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from the command line and from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.buffer.ByteBufUtil got initialized use --trace-class-initialization=io.netty.buffer.ByteBufUtil
io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from the command line and from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator
io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from the command line and from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.buffer.PooledByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.PooledByteBufAllocator
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from the command line). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf
io.netty.buffer.UnpooledUnsafeDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeDirectByteBuf
io.netty.handler.ssl.ReferenceCountedOpenSslContext the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.handler.ssl.ReferenceCountedOpenSslContext got initialized use --trace-class-initialization=io.netty.handler.ssl.ReferenceCountedOpenSslContext
io.netty.buffer.UnpooledDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf
io.netty.channel.epoll.Epoll the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why io.netty.channel.epoll.Epoll got initialized use --trace-class-initialization=io.netty.channel.epoll.Epoll
io.netty.util.AbstractReferenceCounted the class was requested to be initialized at run time (from the command line). To see why io.netty.util.AbstractReferenceCounted got initialized use --trace-class-initialization=io.netty.util.AbstractReferenceCounted
```
</p>
</details>

**Environment:**
 - OS: Windows 10, Linux Container
 - Zeebe Version: 0.26.0-rc1
 - Configuration: default settings

**Comment by npepinpe** [comment] 2021-01-05 09:01
Hi @rezanirumand, it seems like the issue is with running AOT on Netty. I think Netty needs some specific configuration - some classes should be initialized only at runtime and not at build time (which I guess is what you're seeing). You can try building with the following option `-H:+TraceClassInitialization` which should help you figure out how these classes end up initialized at build time, or use the suggested param if you want to do it one by one, e.g. `--trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf`.

Unfortunately this is a non-goal for us at the moment - I can imagine it will be at some point, just not right now. However, if you figure it out, it would probably be helpful for others if you can post it here as well.

**Comment by rezanirumand** [comment] 2021-01-05 11:01
Hi @npepinpe,  Thanks for your comments. I spent couple of hours tracing the classes and setting trace for cause of these issues. It seems the issue is the way zeebe client uses a version of grpc which is not compatible with native-image. Quarkus offers for example its own grpc settings. 

I understand the zeebe project is still in its early phases, but given the nature of microservice architecture and the resource consumption of  non-native applications (~500M compared to 50M memory), I believe making the zeebe client a native-image compaitble would be a very good step to make it to more popular.

**Comment by npepinpe** [comment] 2021-01-06 14:41
That's a good point, and I'd love for it to be possible eventually. As it stands, the core team doesn't have to resources at the moment to make this possible, but I'd be happy to accept a PR for it if the maintenance effort seems low enough (i.e. good tests to ensure we don't break it in the future, easy to pinpoint what needs to be fixed, etc.).

**Comment by aivinog1** [comment] 2021-01-25 10:35
@npepinpe Hi! I'm interested in this (GraalVM, native images) topic, I want to work on this issue. But now I can't give any promises about when I would do it :( But, I think that this okay, since it in the backlog and low prioritized :)

**Comment by npepinpe** [comment] 2021-01-25 14:08
Go for it, from our pov this is a nice to have, we simply don't have the resources to investigate it at the moment. Note that the important outcome here should be:

- How to create a native image with the Zeebe client embedded
- It should be as easy as possible for someone to do this (i.e. ideally no extra configuration needed from the user)
- Our build should break if we introduce changes that would prevent someone from building a native image
- Ideally if the build breaks it shouldn't be too hard to figure out how to fix it

So one outcome would be finding the right changes, but also explaining the reasoning behind them to spread out the knowledge.

**Comment by aivinog1** [comment] 2021-01-27 16:13
@npepinpe, @rezanirumand Hi! I spent around 10 hours making a very simple working example of Zeebe client compiled in the native image: https://github.com/aivinog1/graalvm-sample. So, I think I learn a bit in the current step and I want to share all pitfalls that I encountered :)

First, just start with the JDK logger (you can use an SLF4 facade, but it still needs to be JDK). Because it works out the box: https://www.graalvm.org/reference-manual/native-image/Logging/. Believe me, I spent around 6 to 8 hours to make log4j2 work without success, because of a lot of reflection stuff (it's not so obvious to me, some sort of plugins, that works from reflection, configurations, etc.). And after all, it **doesn't work** on my machine (because nasty stuff in the netty that depends on the log4j2) :(
Second, a simple app, as I shared previously could work very well, but as many functionalities we use, so tricky conditions could be. So, I'm thinking that we should run **the same amount of tests** of the client on the native image.
Third, as I can see now, debugging is pretty easy (if you don't try to figure out why reflection stuff doesn't work), but consumes a large amount of time, because compilation isn't fast as just a building simple jar.

So, I will appreciate it if you could try to run my simple app and share some ideas :)
GraalVM: 
```a.i.vinogradov@vm-dmz-app53 graalvm-sample-logging % java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
a.i.vinogradov@vm-dmz-app53 graalvm-sample-logging %
```

**Comment by npepinpe** [comment] 2021-01-27 17:24
Thanks @aivinog1! If I understand correctly, the repo you linked works? I had issues getting netty to work to be honest, not log4j2.

I see in your pom.xml you have tons of config, could you explain these line by line? I'm trying to understand why/how it works, so if anything breaks we would be able to fix it :slightly_smiling_face: 

```xml
<buildArgs>
                --no-fallback --verbose --allow-incomplete-classpath
                --report-unsupported-elements-at-runtime
                --features=org.graalvm.home.HomeFinderFeature

                --initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder
                --initialize-at-build-time=org.slf4j.impl.JDK14LoggerAdapter
                --initialize-at-build-time=org.slf4j.LoggerFactory

                --initialize-at-run-time=io.netty.buffer.UnpooledDirectByteBuf
                --initialize-at-run-time=io.netty.buffer.AbstractPooledDerivedByteBuf
                --initialize-at-run-time=io.netty.buffer.UnpooledHeapByteBuf
                --initialize-at-run-time=io.netty.handler.ssl.PemValue
                --initialize-at-run-time=io.netty.util.AbstractReferenceCounted
                --initialize-at-run-time=io.netty.handler.ssl.PemPrivateKey
                --initialize-at-run-time=io.netty.buffer.PooledByteBufAllocator
                --initialize-at-run-time=io.netty.buffer.UnpooledUnsafeDirectByteBuf
                --initialize-at-run-time=io.netty.buffer.ByteBufUtil
                --initialize-at-run-time=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf
                --initialize-at-run-time=io.netty.buffer.AbstractReferenceCountedByteBuf
                --initialize-at-run-time=io.netty.buffer.ByteBufAllocator
                --initialize-at-run-time=io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator
                --initialize-at-run-time=io.netty.handler.ssl.OpenSsl
                --initialize-at-run-time=io.netty.internal.tcnative.SSL
                --initialize-at-run-time=io.netty.handler.ssl.ReferenceCountedOpenSslEngine
                --initialize-at-run-time=io.netty.internal.tcnative.CertificateVerifier
                --initialize-at-run-time=io.netty.util.internal.logging.Log4JLogger
                --initialize-at-run-time=io.netty.handler.ssl.JettyNpnSslEngine
                --initialize-at-run-time=io.netty.handler.ssl.JettyAlpnSslEngine$ClientEngine
                --initialize-at-run-time=io.netty.handler.ssl.JettyAlpnSslEngine$ServerEngine
                --initialize-at-run-time=io.netty.handler.ssl.ConscryptAlpnSslEngine
              </buildArgs>
```

**Comment by aivinog1** [comment] 2021-01-28 13:49
@npepinpe Yes, my repo works:
```
a.i.vinogradov@vm-dmz-app53 graalvm-sample-logging % ./target/sample 
Jan 28, 2021 3:57:45 PM org.aivinog1.logging.App main
INFO: Requesting topology with initial contact point localhost:26500
Jan 28, 2021 3:57:46 PM org.aivinog1.logging.App main
INFO: Topology:
Jan 28, 2021 3:57:46 PM org.aivinog1.logging.App lambda$main$1
INFO:     172.23.0.2:26501
Jan 28, 2021 3:57:46 PM org.aivinog1.logging.App lambda$main$0
INFO:       1 - LEADER
Jan 28, 2021 3:57:46 PM org.aivinog1.logging.App main
INFO: Done.
a.i.vinogradov@vm-dmz-app53 graalvm-sample-logging % 
```
Alright, let's dig up on configs. So, as you can see `buildArgs` divided into three sections (you can find descriptions from there: https://www.graalvm.org/reference-manual/native-image/Options/). The first section is about the general compile configuration:
1. `--no-fallback` means that if the compilation will fail the build fails too
2. `--verbose` to see details of the compilation process
3. `--allow-incomplete-classpath` to cheat some problems with classes that you don't have in the classpath. You can easily drop it.
4. `report-unsupported-elements-at-runtime` this is the same as previous
5. `--features=org.graalvm.home.HomeFinderFeature` I don't set the `GRAALVM_HOME` system, so I need to use it to make it works. You can drop it too.
Summary of this section: this section has a debug purpose, you can drop it, and the compilation still works.

The second section is about classes that need to be initialized at runtime. Practically, this is because some class that initialized at build time(you can see the difference in the docs: https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#runtime-vs-build-time-initialization) references in the static block (or variable) to this class. In addition: we can embed this configuration in the dependency: https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/. So, I think this:
```
--initialize-at-build-time=org.slf4j.LoggerFactory
```
should be embedded because this class is part of `slf4j-api` from the `zeebe-client-java` artifact. Other classes should stay only in the end user's configuration.

The third section is the same. So these classes, opposite to the previous one, should be initialized at run time. But I think all netty's classes should be embedded in the `zeebe-client-java` artifact because they depend on it.

So, I think I can provide PR for that issue, but I don't know how to add GraalVM with building the native image in the CI. Also, I don't know how to test it. I'm thinking about compiling and testing [zeebe samples](https://github.com/zeebe-io/zeebe/tree/develop/samples), but I'm not sure. I have an idea to build two docker images of samples (with jar and native compiled) and run the same amount of tests on each container.

Please feel free to ask questions here, or in the Slack :)

**Comment by aivinog1** [comment] 2021-02-04 08:44
From our discussion with @npepinpe:

> I dug up a little and found out that without --allow-incomplete-classpath option project doesn't compile. Then I researched the Quarkus project and copy-pasted some solutions (this is substitutions of real methods that would be invoked) from them (for example https://github.com/quarkusio/quarkus/blob/master/extensions/grpc-common/runtime/src/main/java/io/quarkus/grpc/common/runtime/graal/GrpcNettySubstitutions.java): https://github.com/aivinog1/graalvm-sample/commit/576d43407c3d326e510b4224607ceea69792e23e.
> I'm not good at licensing and all that kind of stuff, so, how can I properly quote their license (it is the Apache license 2) in the Zeebe project? Or should I make some modifications to the code that I'm copy-pasting and then I can push it to the repo? Or is it just fluff and I shouldn't worry at all? :)

**Comment by npepinpe** [comment] 2021-04-18 20:51
I spent some time this weekend on getting a Quarkus example with a Zeebe client to work, and I ended up needing to do things a little differently.

First, you want to add the following dependencies to your project to make sure the GraalVM substitutions are included:

```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-grpc-common-deployment</artifactId>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-grpc-common</artifactId>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-netty</artifactId>
    </dependency>
```

> I'm actually not sure you need `quarkus-grpc-common-deployment`, but you definitely need the other two! This will include the right substitutions and will avoid any need to copy them.

Next, you need to add (or merge with) the following resources, by adding a file to your project's `resources/META-INF/native-image/<groupId>/<artifactId>/resource-config.json`:

```json
{
  "resources": {
    "includes": [
      {
        "pattern": "\\Qclient-java.properties\\E"
      }
    ]
  },
  "bundles": []
}
```

This will ensure that Zeebe's `VersionUtil` can read the correct version.

Then we need to update `resources/META-INF/native-image/<groupId>/<artifactId>/native-image.properties`:

```
Args=--verbose --allow-incomplete-classpath --no-server --no-fallback --report-unsupported-elements-at-runtime \
  -H:+AddAllCharsets \
  -H:+StackTrace \
  --initialize-at-build-time=org.slf4j.LoggerFactory \
  --initialize-at-build-time=org.slf4j.simple.SimpleLogger \
  --initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder \
  --initialize-at-build-time=io.netty.handler.ssl.ApplicationProtocolConfig \
  --initialize-at-build-time=io.zeebe.util.VersionUtil \
  --initialize-at-run-time=io.netty.handler.ssl \
  --initialize-at-run-time=io.netty.internal.tcnative.SSL
```

This simply makes sure we initialize SLF4J at build time, `VersionUtil` (since it needs to read the static version of the Zeebe lib!), and delays initialization of most SSL stuff to run time. This should work with Quarkus 1.13.2.Final and Zeebe 0.26.3.

That said, the main issue I have with this is that if we were to merge anything, then we have to ensure it doesn't break, which requires a small test suite for the native image (at least for the client), and understanding + commitment to maintain it in the future. Nothing too crazy, but we're a little stretched at the moment in terms of resources, so I'm not too keen on increasing the surface of what we have to maintain right now. I imagine this topic will come up again post 1.0 launch, and I'm happy to tackle it at this point. 

I would propose for now that anyone who's interested can propose a community project (either on the [Community Hub](https://github.com/camunda-community-hub/community) or their own repo) which sets up a Quarkus extension for Zeebe (see https://quarkus.io/guides/writing-extensions), which can alleviate all this. On the Zeebe side, I will think a bit more about adding some basic stuff for native image support (for example, at least ensuring the client-java.properties is included, and VersionUtil is initialized at build time, etc.), but I wouldn't start mucking about with settings affecting other libraries.

I will then close this for now.

**Closed by npepinpe** 2021-04-18 20:51 UTC
Labels: Priority: Low, Scope: clients/java, Status: Backlog, Type: Enhancement
