### ISSUE TITLE
"SAXException while parsing input stream" related to the order

### ISSUE THREAD

**Issue by HarryWu-CHN** [camunda-cloud/zeebe#8641] opened 2022-01-25 07:43 UTC
**Describe the bug**

I use `bpmn-python` to genertate the BPMN file, the structure of the BPMN is like:
```
<definitions>
  <bpmndi:BPMNDiagram>
    .....
  </bpmndi:BPMNDiagram>
  <process>
    ......
  </process>
<definitions>
```
It can be opened by Camunda Modeler without any error. However, when I deploy it to Zeebe Broker, the Broker raise **SAXException while parsing input stream**.

When I exchange the position of `bpmndi:BPMNDiagram` and `process`, the problem is solved. The new BPMN is like:
```
<definitions>
  <process>
    ......
  </process>
  <bpmndi:BPMNDiagram>
    .....
  </bpmndi:BPMNDiagram>
<definitions>
```

I don't know whether it is a bug or not. In my view, the above 2 BPMN file are equivalent and the Modeler can open both of them, but the Broker can't.

Looking forward to your reply. Thank you.

**Environment:**
 - Zeebe Version: 1.3.0
 - Camunda Modeler: 4.11.1

**Comment by npepinpe** [comment] 2022-01-25 08:23
Hi @HarryWu-CHN, how did you figure out the workaround? Was the error message helpful? There's [an issue to improve it](https://github.com/camunda-cloud/zeebe/issues/8026), as we think it's often not, so any input there is also useful.

**Comment by npepinpe** [comment] 2022-01-25 08:24
Related to https://github.com/camunda-cloud/zeebe/issues/5490 - however, I wouldn't mark it as duplicate as this is outlining a specific case.

**Comment by npepinpe** [comment] 2022-01-25 08:35
Leaving in the backlog for now, as this won't affect users using the Camunda Modeler, there's immediate feedback, and there's a clear workaround.

**Comment by HarryWu-CHN** [comment] 2022-01-25 09:00
> Hi @HarryWu-CHN, how did you figure out the workaround? Was the error message helpful? There's [an issue to improve it](https://github.com/camunda-cloud/zeebe/issues/8026), as we think it's often not, so any input there is also useful.

I just compared the demo BPMN you provided on the [Quickstart](https://docs.camunda.io/docs/self-managed/zeebe-deployment/local/quickstart/) with my BPMN file, and I finally found it after many tries. The client's error message is useless to me, because I did't know it is the wrong order that raise the SAXException. 

By the way, what is the SAXException?

**Comment by menski** [comment] 2022-01-25 09:04
Not sure if this is a bug, we use the [BPMN 2.0 XSD](https://www.omg.org/spec/BPMN/20100501/BPMN20.xsd) to valid the XML file, and that one defines a sequence where the `process` element which is a `rootElement` has to come before the `BPMNDiagram`

```
<xsd:sequence>
  <xsd:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
  <xsd:element ref="extension" minOccurs="0" maxOccurs="unbounded"/>
  <xsd:element ref="rootElement" minOccurs="0" maxOccurs="unbounded"/>
  <xsd:element ref="bpmndi:BPMNDiagram" minOccurs="0" maxOccurs="unbounded"/>
  <xsd:element ref="relationship" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
```

**Comment by npepinpe** [comment] 2022-01-25 09:06
Is this part of the spec then? /cc @saig0

**Comment by korthout** [comment] 2022-01-25 09:20
@npepinpe Yes, the schema is defined in [the spec](https://www.omg.org/spec/BPMN/2.0.2/PDF) on page 52 chapter 8.2.3, table 8.3, which contains:
```xml
<xsd:element name="definitions" type="tDefinitions"/>
<xsd:complexType name="tDefinitions">
  <xsd:sequence>
    <xsd:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element ref="extension" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element ref="rootElement" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element ref="bpmndi:BPMNDiagram" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element ref="relationship" minOccurs="0" maxOccurs="unbounded"/>
  </xsd:sequence>
  <xsd:attribute name="id" type="xsd:ID" use="optional"/>
  <xsd:attribute name="targetNamespace" type="xsd:anyURI" use="required"/>
  <xsd:attribute name="expressionLanguage" type="xsd:anyURI" use="optional" default="http://
  www.w3.org/1999/XPath"/>
  <xsd:attribute name="typeLanguage" type="xsd:anyURI" use="optional" default="http://www.w3.org/
  2001/XMLSchema"/>
  <xsd:anyAttribute name="exporter" type="xsd:ID"/>
  <xsd:anyAttribute name="exporterVersion" type="xsd:ID"/>
  <xsd:anyAttribute namespace="##other" processContents="lax"/>
</xsd:complexType>
```

**Comment by npepinpe** [comment] 2022-01-25 09:54
Then I would close this as not a bug - I don't see a big value in breaking from the spec here, but of course feel free to comment and disagree :slightly_smiling_face:

**Closed by npepinpe** 2022-01-25 09:54 UTC
Labels: Type: Bug, good first issue, Severity: Low, Impact: Usability, 1.3.0

**Comment by HarryWu-CHN** [comment] 2022-01-25 10:00
Thanks for checking, too! I am happy to know the spec.
